raiden-network/raiden-contracts

requirements.txt

Discovered that `coincurve` was missing when I tried to run the tests.

add coincurve to requirements

---

.travis.yml
.travis/download_solc.sh
README.md
contracts/SecretRegistry.sol
contracts/TokenNetwork.sol
contracts/TokenNetworksRegistry.sol
raiden_contracts/deploy/__main__.py
raiden_contracts/tests/conftest.py
raiden_contracts/tests/fixtures/__init__.py
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/config.py
raiden_contracts/tests/fixtures/secret_registry.py
raiden_contracts/tests/fixtures/token.py
raiden_contracts/tests/fixtures/token_network.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/fixtures/utils.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_open.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_secret_registry.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py
raiden_contracts/tests/utils.py
raiden_contracts/utils/config.py
raiden_contracts/utils/logs.py
raiden_contracts/utils/sign.py
raiden_contracts/utils/sign_utils.py
setup.cfg

fixes https://github.com/raiden-network/raiden-contracts/issues/2
fixes https://github.com/raiden-network/raiden-contracts/issues/4
(LC:)
- add more tests and fixtures
- deploy script uses web3 directly; compiled contracts data must be provided (done with `populus compile`
Smart contract changes:
- `TokenNetworkRegistry` -> `TokenNetworksRegistry`
- block numbers are `uint256` instead of `uint64`
- add `chain_id` to `TokenNetwork`, `TokenNetworksRegistry` constructors 
- `event ChannelClosed(uint256 channel_identifier, address closing_address);` (replaced old argument `closing_participant`, because we provide the address of the caller - can be a 3rd party)
- support for closing & updating the channel without any existent off-chain transfers ('nonce' issue: …

Add SC Tests/Fixtures and some SC changes

---

contracts/TokenNetwork.sol
raiden_contracts/tests/utils.py

There was no good reason to change `closing_address` to `closing_participant`.
https://github.com/raiden-network/raiden-contracts/pull/15#issuecomment-375062996

Revert to initial name for ChannelClosed event - closing_participant argument

---

.travis.yml
setup.py

Reason: 
- stay in line with Raiden Network project
- support new string formatting such as `f"Event '{event_name}' not found.”`

Update python to 3.6 - travis

---

.travis.yml
README.md
raiden_contracts/contract_manager.py
raiden_contracts/data/contracts.json
raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_contract_manager.py
raiden_contracts/utils/utils.py
requirements-dev.txt
requirements.txt
requirements_dev.txt
requirements_populus.txt
setup.py

Remove `populus` dependency from common utils functions.
Refactor dependencies, provide compiled data.
Removed contract manager code. There is no reason to keep it because we provide the compiled data.

Fix requirements, provide compiled data

---

contracts/TokenNetwork.sol
raiden_contracts/tests/test_channel_update_transfer.py

As discussed in https://github.com/raiden-network/raiden-contracts/pull/15#issuecomment-375062996, `updateTransfer` should fail if the `nonce` is 0.
(more updateTransfer tests will be added in another PR)

updateTransfer should fail if nonce is 0

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/lib/ECVerify.sol
raiden_contracts/contracts/test/SignatureVerifyTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/utils.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_recover_from_signature.py
raiden_contracts/utils/sign.py
raiden_contracts/utils/sign_utils.py

We can reuse the `ECVerify` library for all projects. It is better to have it separately.
Small refactoring for the address recover code.
Added tests.

Extract address verification in a separate reusable contract

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_cooperative_settle.py
raiden_contracts/utils/sign.py

fixes https://github.com/raiden-network/raiden-contracts/issues/49
Adds support for an instant channel close & settle if both participants exchange signatures on balances calculated off-chain.

Cooperative settle

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/token_network.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_cooperative_settle.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_open.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_recover_from_signature.py
raiden_contracts/utils/sign.py

fixes https://github.com/raiden-network/raiden-contracts/issues/40
Structural changes for limiting the number of channels between two nodes to 1.
All changes stem from changing the `channel_identifier` from a monotonically increasing `uint256` to the `keccak256` of the two channel participant addresses, ordered lexicographically.
Changes:
- `channel_identifier` from `uint256` to `bytes32` - for all events
- `openChannel` returns `bytes32`
- `setDeposit(address participant, uint256 total_deposit, address partner)`
- getters:
- `function getChannelIdentifier(address participant, address partner)` returns `bytes32`
- `function getChannelInfo(address participant1, address participant2)` returns `(channel_identifier, settle_block_number, state)`
- `function getChannelParticipantInfo(address …

TokenNetwork - 2 nodes can have maximum 1 channel

---

raiden_contracts/contracts/SecretRegistry.sol
raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/config.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_cooperative_settle.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_open.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_secret_registry.py
raiden_contracts/tests/utils.py

fixes https://github.com/raiden-network/raiden-contracts/issues/45 (overflow and underflow checks)
fixes https://github.com/raiden-network/raiden-contracts/issues/32 (fix nonce check in closeChannel)
fixes https://github.com/raiden-network/raiden-contracts/issues/47 (group invariants)
fixes https://github.com/raiden-network/raiden-contracts/issues/53 (`unlock_amount` can be `0`)
Mostly groups and adds invariant checks + some tests to make sure they work as assumed.

Core contracts - add & group invariant checks

---

raiden_contracts/deploy/__main__.py

Hello,
While trying to run contract deployment i came across the fact that `contracts.json` will contain `bin` instead of `bytecode`. Which matches the requested `output_values` here: https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/contract_manager.py#L67
My solc version is as follows:
```
solc, the solidity compiler commandline interface
Version: 0.4.23+commit.124ca40d.Linux.g++
```

Use 'bin' as the source of a contracts bytecode

---

raiden_contracts/tests/conftest.py
raiden_contracts/tests/fixtures/__init__.py
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/tests/fixtures/secret_registry.py
raiden_contracts/tests/fixtures/test_contracts.py
raiden_contracts/tests/fixtures/token.py
raiden_contracts/tests/fixtures/token_network.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_secret_registry.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py

- moves contract fixtures from `raiden-libs` to `raiden-contracts`
- also fixes fixture names
- do not merge until other repos are ready for the change!

Move test fixtures from libs to contracts

---

contracts
setup.py

- it was only required for populus build; now it can go

Remove `contracts` symlink

---

raiden_contracts/contract_manager.py
requirements.txt

- adds `ast` output to compile options to make `py-solc` happy

Fix contract compilation with `py-solc` >= 2.2.0

---

raiden_contracts/contracts/EndpointRegistry.sol
raiden_contracts/contracts/MonitoringService.sol
raiden_contracts/contracts/SecretRegistry.sol
raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/HumanStandardToken.sol

fixes https://github.com/raiden-network/raiden-contracts/issues/86
- fallback functions must be `external` (https://github.com/ethereum/solidity/blob/develop/Changelog.md#0417-2017-09-21)
- `keccak256` can only be used with a single `bytes` argument; `abi.encodePacked` can be used to tightly pack arguments (https://github.com/ethereum/solidity/blob/develop/Changelog.md#0424-2018-05-16)

Fix upcoming solc 0.5.0 breaking changes

---

raiden_contracts/cm_test/test_contract_manager.py
raiden_contracts/contract_manager.py
raiden_contracts/tests/fixtures/token.py
setup.py

- fixes exception that is being raised when CM is initialized with a  single directory as its constructor argument
- better filtering of files that will be compiled
- removes duplicate token fixture

Raiden integration: update ChannelManager

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/utils.py

fixes https://github.com/raiden-network/raiden-contracts/issues/106
- fixes settlement calculations for cases in which no/old balance proofs are provided.
- initial tests that must be extended properly.
Notes:
`d1` = p1's deposit
`w1` = p1's withdrawn amount
`t1` = p1's transferred amount to p2
`t2` = p2's transferred amount to p1
```
p1_balance = d1 + t2 - w1 - t1
```
Problem cases:
```
t2 = [0, real_t2) -> p1 has provided no/old balance proof -> p1_balance = 0
t1 = [0, real_t1) -> p2 has provided no/old balance proof -> p1_balance = total_available_deposit
```

Fix settlement calculations

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/CustomToken.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_monitoring_service.py
raiden_contracts/tests/test_token.py

fixes https://github.com/raiden-network/raiden-contracts/issues/122
When calling `setTotalDeposit`, make sure the two participant's deposits don't overflow when added. This is very important for the settlement calculations.

Add channel deposit overflow check & test

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_monitoring_service.py
raiden_contracts/tests/test_print_gas.py

This should fix the overflow issue for the old `deposit + transferred_amount` approach, demonstrated in https://github.com/raiden-network/raiden-contracts/pull/116/files#diff-cf6314cb143087ba6788de239e94298aR7 and mentioned in the thread started here: https://github.com/raiden-network/raiden-contracts/issues/117#issuecomment-395758666 
TODO:
(update: the following is not necessary - detailed explanation in https://github.com/raiden-network/raiden-contracts/pull/123#pullrequestreview-128277844)
- if possible, create test that would trigger an underflow when subtracting the withdrawn amount, to test that we handle it correctly; think some more if this approach is fair.
```
// Subtract already withdrawn amount
(participant1_amount, ) = failsafe_subtract(
participant1_amount, …
```

Fix settlement overflow on transferred amount

---

raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/utils.py

The function can be used to compare expected settlement
amounts and those that a realized onchain mod 2**256.

Adding get_onchain_settlement_amounts function for testing

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/utils.py

Fix how locked amounts are computed at settlement
Fixes #127
```
P1 = participant1
D1 = deposit P1
W1 = withdrawn P1
T1 = transferred P1 -> P2
L1 = pending transfers P1 -> P2
A1 = amount to be received by P1 at settlement 
P2 = participant2
D2 = deposit P2
W2 = withdrawn P2
T2 = transferred P2 -> P1
L2 = pending transfers P2 -> P1
A2 = amount to be received by P2 at settlement
DC = D1 + D2 - W1 - W2 = current channel deposit
```
To simplify calculations, we artificially require the `settleChannel` arguments to be ordered:
```
T2 + L2 >= T1 + L1
```
https://github.com/raiden-network/raiden-contracts/blob/1046322d015a4ec06f6ad0b9961db194399f3563/raiden_contracts/contracts/TokenNetwork.sol#L882-L884
This comes from the way we compute the maximum receivable amount for `P1`
```
A1max = (T2 + …
```

Fix how locked amounts are computed at settlement for old balance proof with high locked amount

---

raiden_contracts/contracts/MonitoringService.sol
raiden_contracts/contracts/RaidenServiceBundle.sol
raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/TokenNetworkRegistry.sol
raiden_contracts/contracts/test/CustomToken.sol
raiden_contracts/contracts/test/HumanStandardToken.sol
setup.py

Since ContractManager already construct path remappings when invoking `solc`, this PR changes smart contracts to have them use `raiden/...` import path instead of `./`
Resolves https://github.com/raiden-network/raiden/issues/162

Use remappings with import

---

raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_withdraw.py
raiden_contracts/tests/test_unit_internals.py
raiden_contracts/tests/unit/test_settle_timeout_invariant.py
raiden_contracts/tests/unit/test_unit_internals.py

Contribution to #92, fixes #129. The unit tests from /raiden have so far been moved to raiden-contracts according to this mapping: 
```
**raiden/test_auxiliary_netting_channel -> raiden-contracts/test_unit_internals**
test_min_uses_usigned -> test_unit_internals.test_min_uses_usigned
test_max_uses_unsigned -> test_unit_internals.test_min_uses_usigned
test_min -> test_unit_internals.test_min
test_max -> test_unit_internals.test_max
test_recoverAddressFromSignature -> test_unit_internals.test_recoverAddressFromBalanceProof,
-> test_recoverAddressFromBalanceProofUpdateMessage, 
-> test_recoverAddressFromCooperativeSettleSignature,                     
-> test_recoverAddressFromWithdrawMessage
test_merkle_proof_one_lock -> computeMerkleRoot does not exist anymore, removed
test_merkle_proof …
```

unit tests for TokenNetwork internals

---

requirements.txt

> Could not find a version that satisfies the requirement eth-pm==0.1.0-alpha.17
Seems `eth-pm==0.1.0-alpha.17` is missing. `web3 < 4.4.0` does not have an `eth-pm` dependency.
Same issue as https://github.com/ethereum/web3.py/issues/940

Fix web3 dependency on missing eth-pm==0.1.0-alpha.17

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_unlock.py

fixes https://github.com/raiden-network/raiden-contracts/issues/157
Previously, the `locksroot` was not linked to the participant address that it belonged to. This allowed any of the two participants to claim the locked token amounts corresponding to that `locksrooot`. Or event 1 participant to `unlock` both `locksroot`s from the two balance proofs.
This commit is simplifying the storage of the data needed to unlock the pending transfers and links the `locksroot` to a participant's address, by just using:
```
mapping(bytes32 => uint256) locksroot_identifier_to_locked_amount;
```
where the key is `keccak256(abi.encodePacked(channel_identifier, participant, locksroot));`
and the value is the `locked_amount`
The business logic is: `locksroot` is the merkle tree root of the pending transfers …

Fix locksroot & locked amount storage after balance proofs are updated

---

requirements.txt

Version `4.4.0` triggered `Could not find a version that satisfies the requirement eth-pm==0.1.0-alpha.17`. This was fixed in `4.4.1`, as suggested in https://github.com/raiden-network/raiden-contracts/pull/161#issuecomment-401444925

Update web3 dependency to >=4.4.1

---

raiden_contracts/tests/test_channel_settle.py

As I mentioned in https://github.com/raiden-network/raiden-contracts/pull/167#discussion_r200605284 and https://github.com/raiden-network/raiden-contracts/pull/167#discussion_r200606265
I think it is good to add these checks even though the settlement algorithms are used to automatically check the participant balances. We can have errors in those algorithms, so they should be used as an additional check.  For simple tests where the result is clear, I think we should also have a direct balance check.

Additional balance checks in settlement tests

---

.travis.yml
raiden_contracts/cm_test/test_contract_manager.py
raiden_contracts/contract_manager.py
raiden_contracts/tests/fixtures/contracts.py
setup.py

This is a small refactor of the `ContractManager` in preparation for raiden-network/raiden#1550. Also fixes #125.

Simplify contract manager

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_cooperative_settle.py
raiden_contracts/tests/test_channel_open.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_channel_withdraw.py
raiden_contracts/tests/test_monitoring_service.py
raiden_contracts/tests/utils.py
raiden_contracts/utils/events.py

fixes https://github.com/raiden-network/raiden-contracts/issues/141
The issue described a replay attack possible after reopening a settled channel. Old balance proofs could have been used to cheat, because there was way to differentiate between the old and new signed messages.
Two options were discussed:
1. Adding the block number at which the channel was opened in the signed messages
2. Making `channel_identifier` unique with either adding the `open_block_number` or an increasing nonce (counter)
**Option 1:**
- saving `open_block_number` in the channel state
- adding `open_block_number` to all signed messages
- adding `open_block_number` to all channel events
-> this also means changes to the Raiden client
**Option 2** (suggested by @hackaugusto):
- add a global channel counter that …

Add channel counter - fix replay attack on reopened channels

---

.gitignore
.travis.yml
MANIFEST.in
raiden_contracts/contract_manager.py
setup.py

Previously `setup.py` would always trigger a recompilation of `contracts.json`. Even when installing from an `sdist` (where no `solc` might be available). This defeats the purpose of having the precompiled archive in the first place.
This adds a checksum to the precompiled `contracts.json` in order to prevent recompilation attempts in cases where the existing archive already exists.
Also changes the contracts storage to gzipped JSON to save space (~250k vs. 25k).
Also also switches Travis to Python 3.6 to be in line with the other Raiden repos.
Fixes #179

Prevent needless recompilation of precompiled contracts

---

.bumpversion.cfg
.travis.yml

Adds deploy job to `.travis.yml` that is triggered whenever a tag is added.
This has been tested with my PyPi account. Pushing to PyPi won't work unless `.travis.yml` is updated with a correct secure hash for `raiden_pypi_automated` user.

Add PyPi deploy job to Travis

---

raiden_contracts/contracts/test/CustomToken.sol
raiden_contracts/tests/test_token.py

Adds a `mintFor()` method to the `CustomToken` test contract which will be used by the testnet scenario player.

Add helper for scenario player to CustomToken

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/utils/events.py

Fixes https://github.com/raiden-network/raiden-contracts/issues/196
Needed for keeping track of balance data updates more easily from the Raiden client & Monitoring Service
- add `nonce` as argument to `NonClosingBalanceProofUpdated` event
- fix & extend test for the event

Add nonce as argument to NonClosingBalanceProofUpdated event

---

raiden_contracts/contracts/TokenNetwork.sol

the bool is not being packed anymore because the suround types were
expanded to a word

removed outdated comment

---

raiden_contracts/contracts/TokenNetwork.sol

Note: I did not check how much extra gas is being used for the conversion from the enum to uint8
- The first element of the enum starts with the value 0, therefor that
is used for the inexisting state.
- Because of storage optimization the state is stored in a uint8,
therefor the enum value must be converted to from uint8.

Added enum type represent the channel state

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_open.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_channel_withdraw.py

Please review and merge after https://github.com/raiden-network/raiden-contracts/pull/198
As discussed in https://github.com/raiden-network/raiden-contracts/issues/202 and https://github.com/raiden-network/raiden-contracts/issues/193
Link the unlock data to a channel_identifier because we can currently have a new channel opened between two participants while still having tokens to unlock from previous channels between the same participants.
This makes it easier for the Raiden client to keep track of channel data that still is stored on-chain.
```
// returns participant's: deposit, withdrawn_amount, is_the_closer, balance_hash, nonce, locksroot, locked_amount
// `participant` - sends the pending transfers
// `partner` - receives claimable locked amount from `participant`'s transfers …
```

 Refactor unlock data storage in TokenNetwork, link to channel identifier

---

raiden_contracts/contracts/TokenNetwork.sol

After https://github.com/raiden-network/raiden-contracts/pull/212 there was two additional parameters added to `getChannelInfo` but the docstring was not updated. This PR updates the docstring.
Also it adds a check that the participant addresses are not the same.

Add docstring for getChannelInfo params

---

raiden_contracts/contracts/EndpointRegistry.sol

The comments were not in line with Natspec for Solidity (https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format) and the compiler could not return the user & dev docs.
Now, the comments are aligned with Natspec.

EndpointRegistry fix Natspec

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol

Clarify naming and function scope:
Data needed for an `unlock` cannot be updated. If existent, is written to storage only one time, when calling `settleChannel`.

storeUnlockData instead of updateUnlockData to clarify scope

---

raiden_contracts/contracts/EndpointRegistry.sol
raiden_contracts/tests/test_endpointregistry.py
raiden_contracts/utils/events.py

After https://github.com/raiden-network/raiden-contracts/pull/217 there are some mostly cosmetic changes I would like to do to the EndpointRegistry:
- Reword some comments a bit
- Remove the [at]dev natspec as it's not needed and it was just a copy of [at]notice
- Be consistent in the naming. We were using both socket and endpoint to refer to the same thing. A TCP socket is one type of endpoint, but since it's an endpoint registry I think using that term everywhere is better.

Endpoint registry cosmetic

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/TokenNetworkRegistry.sol
raiden_contracts/contracts/lib/ECVerify.sol

(update: this is actually a breaking change in solc `0.5.0`, we will need these changes)
`address(0x0)` is a more specific type.
Using `0x0` is not a bug or a current issue with `solc 0.4.24`. However, if we want to implement stronger types (e.g. https://github.com/raiden-network/raiden-contracts/issues/210), using `address()` is a good idea.
Note that the current contract address cannot be retrieved with `this` in the EVM anymore, we need to use `address(this)`. The proposed change is therefore in line with Solidity changes.

Use address(0x0) instead of 0x0 for input checks of type address

---

raiden_contracts/contracts/EndpointRegistry.sol
raiden_contracts/tests/test_endpointregistry.py

The smart contract function address_by_endpoint allowed a malicious node
to set its address for an endpoint which it did not control. The
functionality was not used and buggy, this removes it.

Removed address_by_endpoint from the endpoint registry

---

raiden_contracts/contracts/TokenNetwork.sol

fixes https://github.com/raiden-network/raiden-contracts/issues/242
A test was not added, because this overflow can only happen if the token implementation of the `transfer` function is incorrect.

Add cooperativeSettle overflow check on balances addition

---

raiden_contracts/contracts/TokenNetwork.sol

fixes https://github.com/raiden-network/raiden-contracts/issues/244
Fix confusing naming of variables in the settlement algorithm. Also fix incorrect comment.

Use participant1_net_max_received instead of participant1_net_max_transferred

---

raiden_contracts/contracts/TokenNetwork.sol

Reorder withdraw checks
**Update**: Case detailed previously is impossible (we have correct state checks in `setTotalWithdraw` & transactions are atomic even when internal transactions happen).
However, I still consider it good practice to have the checks before the external function call / storage change.

Reorder withdraw checks

---

raiden_contracts/contracts/TokenNetwork.sol

Fixes the issue from this thread: https://github.com/raiden-network/raiden-contracts/issues/47#issuecomment-413893255 stemmed from the fact that the code is less readable when the checks do not follow the implementation logic, but are artificially grouped together.
> the beginning of a function starts with the requirements, first validating/requiring the value inputs, then the code is followed by the pure computation, which is followed by the validation of the computation and side-effects, and the code finishes with the asserts/invariants that must be true after the execution of the code.
- check function inputs
- check other preconditions to the state changes that will be done
- perform actions and immediately check if these actions succeeded
- check all other invariants at the end

Reorder checks again

---

raiden_contracts/contracts/TokenNetwork.sol

In line with `0.5.0` solc breaking changes regarding the new ABI encoder.

Use abi.encodeWithSignature for external calls

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_withdraw.py
raiden_contracts/tests/unit/test_unit_internals.py

Removes redundant partner argument from `setTotalWithdraw`, as described in  #238. Additionally, the function was refactored to be more clear and readable, as discussed in #47. Closes #238.

Removes redundant partner argument from setTotalWithdraw.

---

raiden_contracts/constants.py
raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/test_contracts.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/unit/test_unit_internals.py
raiden_contracts/tests/unit/test_unit_signatures.py
raiden_contracts/utils/sign.py

Fixes https://github.com/raiden-network/raiden-contracts/issues/241
I also split the `TokenNetworkInternalsTest` into 3 contracts, because the bytecode size was too big for deployment after the signature changes.
Compatibility with EIP191 & `eth_sign`:
```
\x19Ethereum Signed Message:\n" + len(message) + message
message = <token_network_address> <chain_id> <message_type_id> <message specific data to sign>
```
```
string public constant signature_prefix = '\x19Ethereum Signed Message:\n';
```
Message content is tightly packed as described here: https://solidity.readthedocs.io/en/v0.4.24/abi-spec.html#abi-packed-mode
Python tests implementation: https://github.com/raiden-network/raiden-contracts/pull/252/commits/1569bb635b178c9683c9714b0c92dff4899b4afd#diff-6180c16583e73c52c0366184d36015f9 …

Use a eth_sign and EIP191 compatible signature format

---

requirements.txt

Raiden-libs updated its `coincurve` dependency. No breaking changes on this update.

Sync dependency with raiden-libs

---

raiden_contracts/contract_manager.py
setup.py

The order in which packages are installed is not guranteed by pip / setuptools therefore we need to include `py-solc` in `setup_requires` to make sure it's available during the initial installation / wheel building in a fresh (v)env. Otherwise it can lead to situations where the `contracts.json.gz` can't be built even though all dependencies are available.
Required by: raiden-network/raiden#2349

Fix contract compilation during initial install

---

Makefile
setup.py

- adds `make release` target - solc is required for building a release
if RAIDEN_SOLC_REQUIRED environment variable is set
- removed check for `py-solc` module (it's a `setup.py` dependency now)
Fixes #266

Check for solc when doing a release

---

raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_settle_unlock_state.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/utils/utils.py
raiden_contracts/utils/utils.py

fixes https://github.com/raiden-network/raiden-contracts/issues/132
Linked issue: https://github.com/raiden-network/raiden-contracts/issues/188. This PR implements tests for old balance proofs. I manually created examples for the old balance proofs that can exist for a pair of last valid balance proofs.
- added values for balance proofs edge cases, mimicking old balance proofs
- removed the tests that only tried to mimic old balance proofs with the same `transferred + claimable_locked` sum (added manual values for this); these tests are redundant and they were not implemented correctly; it is hard to implement this correctly, because there are constraints on the maximum locked amount that can exist in a valid balance proof
- added balance tests to make sure that with an old balance proof, …

Settle unlock tests refactor

---

.gitignore
raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/utils.py
requirements-dev.txt
setup.cfg

- unlocked account on the ethereum node is no longer required
- script now uses user-supplied privkey
- better deployment options (raiden contracts/token/token registration)
- test for the functions used by the scripts
Fixes #259

New deployment script

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_cooperative_settle.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_withdraw.py
raiden_contracts/tests/unit/test_unit_signatures.py
raiden_contracts/tests/utils/utils.py

fixes https://github.com/raiden-network/raiden-contracts/issues/265
Please do not merge this until I have the contract limits PR functional on top of this one.
Issue: TokenNetworkRegistry bytecode is too big for deployment if we try to implement https://github.com/raiden-network/raiden-contracts/issues/262 and https://github.com/raiden-network/raiden-contracts/issues/263
We might go with either:
- (**favorite option until now**) remove code that is unimplemented in Raiden: https://github.com/raiden-network/raiden-contracts/pull/270 (remove `cooperativeSettle` & `setTotalWithdraw`)
- move some part of the code in a library https://github.com/raiden-network/raiden-contracts/pull/264 (implemented just in case)
Please do not merge this until I have the contract limits PR functional on top of …

Comment out cooperativeSettle & setTotalWithdraw temporarily

---

raiden_contracts/tests/fixtures/channel_test_values.py

As mentioned in https://github.com/raiden-network/raiden-contracts/pull/189#discussion_r217093458
and in https://github.com/raiden-network/raiden-contracts/pull/189#discussion_r216992619, we now test manually constructed balance proofs (old test was wrong, took more testing time).

Fix comment for the settle&unlock old balance proof tests

---

raiden_contracts/contracts/TokenNetwork.sol
raiden_contracts/contracts/TokenNetworkRegistry.sol
raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
raiden_contracts/tests/fixtures/token_network.py
raiden_contracts/tests/test_deprecation_switch.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py

fixes https://github.com/raiden-network/raiden-contracts/issues/263
To be merged after https://github.com/raiden-network/raiden-contracts/pull/270

Deprecation switch for Bug Bounty release

---

raiden_contracts/tests/test_channel_settle_unlock_state.py

Turn three similiar tests into one parametrized one to avoid a bit of code duplication in the setup. 
Despite our worries in the issue discussion, the tests do not seem to run any slower this way. I ran both versions a couple of times.
Fixes issue #273

Avoid code duplication in settle&unlock tests

---

raiden_contracts/tests/test_channel_deposit.py

Added tests:
- deposits should fail if channel is not in "Opened" state
- deposits should fail for wrong channel + additional checks
Added more checks for the `test_deposit_channel_state` test.

More tests for TokenNetwork.setTotalDeposit

---

raiden_contracts/tests/test_channel_close.py

- added `closeChannel` test, to check that if `nonce = 0`, then no balance data is stored in the `TokenNetwork` contract
- cleaned up `test_close_channel_state` test for `closeChannel` and added ETH & token balance checks

Added nonce=0 closeChannel test, clarified state test for closeChannel

---

raiden_contracts/tests/fixtures/utils.py
raiden_contracts/tests/test_contract_limits.py

fixes https://github.com/raiden-network/raiden-contracts/issues/281
- test that users cannot deposit anymore tokens or create new channels after the token network limit is reached
- skipped because it takes >4h to run with the hardcoded values; it can be run faster locally by lowering the `token_network_deposit_limit`.
This can be more easily tested if the limits were not hardcoded, but I DO NOT advise for not hardcoding the limits, which would mean passing them as constructor arguments for the `TokenNetworkRegistry` contract.

Add a test for the token network limit

---

raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_unlock.py

- move unlock test from `test_channel_settle` to `test_channel_unlock`
- add wrong state test for `settleChannel` - check that settleChannel cannot be called when the channel is in a wrong state
- add `settleChannel` test for wrong balance values

Add more tests for settleChannel

---

raiden_contracts/tests/test_channel_unlock.py

- Replace `EMPTY_MERKLE_ROOT` with `EMPTY_LOCKSROOT` from constants.py (we use this now)
- Add unlock test for different channel, same participants
- Add `test_channel_unlock_no_locked_amount_fail` - unlock fails if there is no amount locked in the `TokenNetwork` contract
- Add more checks for unlock tests

Add more tests for TokenNetwork unlock

---

raiden_contracts/tests/fixtures/config.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/utils/utils.py

To be merged after https://github.com/raiden-network/raiden-contracts/pull/289
Add tests for `getMerkleRootAndUnlockedAmount`
- check merkle tree components length
- check odd & even number of merkle tree components
- check wrong order of lockhashes - compare resulted merkle roots when the order of lockhashes is changed.
Add test for `getLockDataFromMerkleTree`

More tests merkle tree

---

requirements-dev.txt

Use the pip `raiden-libs` release instead of installing from git.
We need `raiden-libs>=0.1.6` because previous versions cause errors in the deploy script.

Update raiden-libs dev dependency to use pypi release

---

README.rst
raiden_contracts/deploy/__main__.py

Previously the common options where given for the base command `main`,
which destroyed the `--help` on subcommands (see
https://github.com/pallets/click/issues/295 ).
This solves it by moving all common options into a new decorator and
factoring the previous main commands logic into a setup function.
Now the common structure is `deploy CMD OPTIONS` instead of the previous
`deploy COMMON_OPTIONS CMD CMD_OPTIONS`.

Share common options through subcommand decorator

---

MANIFEST.in
raiden_contracts/contract_manager.py
raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

fixes https://github.com/raiden-network/raiden-contracts/issues/331
- added deployment info file save & verification as a separate step from the actual deployment
- used the above verification script in the deployment script test & added some more checks
- this removed the fake deployment info file that was created during the test & could be wrongly included in a package release
- restrict what files can go in the release, to avoid cases where we have private network deployment files created in the `data` directory.
- add option to not store deployment info when running the deploy script

Fix deployment test & restrict release files

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/deprecation_switch_testnet.py

fixes https://github.com/raiden-network/raiden-contracts/issues/332
```
python -m raiden_contracts.tests.deprecation_switch_testnet --private-key $PRIVATE_KEY --rpc-provider http://127.0.0.1:8545 --gas-price 40 --gas-limit 6000000 --wait 600
```
- deploys the Raiden contracts
- deploys a token and registers a TokenNetwork
- checks that channels can be created and tokens deposited
- activates the deprecation switch
- checks that channels cannot be created anymore and tokens cannot be deposited
Ran the test successfully on Ropsten & Rinkeby.

Add a deprecation switch test script to be ran on a testnet

---

raiden_contracts/constants.py

This Enum has been removed from the client and can safely be removed from here too

Remove unused enum NetworkType

---

README.rst
raiden_contracts/deploy/etherscan_verify.py
requirements-dev.txt

fixes https://github.com/raiden-network/raiden-contracts/issues/319
Rough script to verify contracts. To be used like:
```
python -m raiden_contracts.deploy.etherscan_verify --apikey ETHERSCAN_APIKEY --contract-name EndpointRegistry --chain-id 3
python -m raiden_contracts.deploy.etherscan_verify --apikey ETHERSCAN_APIKEY --contract-name SecretRegistry --chain-id 3
python -m raiden_contracts.deploy.etherscan_verify --apikey ETHERSCAN_APIKEY --contract-name TokenNetworkRegistry --chain-id 3
```
- Etherscan verification works for `EndpointRegistry` and `SecretRegistry`.
- For some reason, the verification fails for `TokenNetworkRegistry`. However, if you manually verify on Etherscan using the `flatten.sol` source created by the script in `raiden_contracts/deploy/` and the data printed by the …

Script for verifying contracts with etherscan

---

raiden_contracts/contracts/lib/ECVerify.sol

The value `v` from the signature is one byte, but `mload` reads 32 bytes.  The code and the comment disagreed which 32 bytes are taken.
I could change the comment or change the code.  I'm playing safe and changing the comment in this PR.

Fix comment about signature parsing

---

raiden_contracts/contracts/services/MonitoringService.sol

It seemed possible to me that a subtraction of token amounts underflows.

Don't give rewards from too small balances

---

raiden_contracts/tests/unit/test_recover_from_signature.py

This is a small beginning of https://github.com/raiden-network/raiden-contracts/issues/357 .

Add docstrings to unit tests in recover_from_sig

---

raiden_contracts/tests/utils/__init__.py
raiden_contracts/tests/utils/address.py
raiden_contracts/tests/utils/config.py

To be merged after https://github.com/raiden-network/raiden-contracts/pull/379
Moving `make_address` to `raiden_contracts/tests/utils/config.py`. Removed `raiden_contracts/tests/utils/address.py`, as it was the only thing that it contained.

Move make_address

---

raiden_contracts/tests/test_token_network_registry.py

Moreover, added some useful cases to try invalid constructor arguments
containing wrong challenge period durations.

Document tests about TokenNetworkRegistry contract

---

raiden_contracts/deploy/__main__.py

I introduced an overwrite of the `contract_manager` when adding checksum verification, that recompiled the contracts instead of using the precompiled data.
This PR fixes this issue, found in https://github.com/raiden-network/raiden-contracts/issues/397

Fix bug in deployment that recompiled the contracts

---

raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_channel_withdraw.py
raiden_contracts/tests/test_print_gas.py

This PR adds docstrings to the remaining tests (as pointed out https://github.com/raiden-network/raiden-contracts/issues/357#issuecomment-452009411).

Remainig docstring on tests

---

.gitattributes

This adds nice syntax highlighting for solidity (`*.sol`) to the github web interface :)
See: ethereum/solidity#2681

Add github highlighting for .sol

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/utils/transaction.py

This fixes #423.
#347 might be better, but I haven't tried with the Parity fast-sync client.

Fix deprecation_switch_testnet.py on Parity light client

---

raiden_contracts/tests/test_deploy_script.py

- test `deploy_token_contract()` used in the deployment script
- test `register_token_network()` used in the deployment script
The test checks if the above functions work correctly in the happy case,
to make sure no code dependencies have been changed, affecting the deployment script.
The test does not check however that the cli command works correctly.

Add tests for deployment script functions: `token` & `register`

---

RELEASE.rst

If `v0.9.0` is released properly, we can remove a warning in `RELEASE.rst`.

The release process has been tested

---

raiden_contracts/deploy/__main__.py

The gas price configuration was not used during raiden_contracts.deploy register command execution.
This commit fixes https://github.com/raiden-network/raiden-contracts/issues/456.

--gas-price configuration in deploy register

---

raiden_contracts/tests/test_contracts_compilation.py

This commit uncomments checks that the deployment files exist for the
test networks.
This fixes https://github.com/raiden-network/raiden-contracts/issues/444

Uncomment checks for deployment files

---

MANIFEST.in
RELEASE.rst

This fixes #492.
[no ci] <-- seems not working https://github.com/raiden-network/raiden-contracts/issues/507

Document gas measuring for releasing

---

raiden_contracts/deploy/__main__.py

during deployment.
This closes https://github.com/raiden-network/raiden-contracts/issues/483 .

Check MonitoringService's user_deposit variable

---

raiden_contracts/deploy/__main__.py

Please review #512 first.
Whenever `verify_deployed_contract()` was called, very similar lines were printed, and `constructor_arguments` were computed.  This PR moves these common lines into the function body of `verify_deployed_contract()`.
I tried the resulting deploy script on Kovan.
This PR is a step in the refactoring of `verify_deployed_contracts()` (#502).  This is a second try after #505.

More useful verify_deployed_contract() and fewer lines around its usage

---

raiden_contracts/deploy/__main__.py

I was browsing Web3.py documentation and what saw I meant was called [ContractFunction](https://web3py.readthedocs.io/en/stable/contracts.html?highlight=transact#web3.contract.ContractFunction.transact).

Fix type annotation of ContractDeployer.transact()

---

raiden_contracts/deploy/etherscan_verify.py

Before this PR, when I gave an unknown chain_id to `etherscan_verify.py`, I got an irrelevant error message:
```
File "raiden-contracts/raiden_contracts/contract_manager.py", line 284, in get_contracts_deployed
raise ValueError(f'Cannot load deployment data file: {ex}') from ex                             
ValueError: Cannot load deployment data file: [Errno 2] No such file or directory: 'raiden-contracts/raiden_contracts/data/deployment_private_net.json'
```
After this PR, I get
```
Unknown chain_id 89
```

clearer error message when etherscan_verify.py gets an unknown chain_id

---

raiden_contracts/utils/join-contracts.py

Before this commit, join-contracts.py without --import-map failed with
an error message:
```
File "utils/join-contracts.py", line 66, in main
import_map = json.loads(import_map)
File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This issue fixes the problem by changing the default value from "" to
"{}".
I know this script is not used anywhere yet, so [skip ci].

Fix join-contracts.py without --import-map

---

.gitignore
raiden_contracts/deploy/etherscan_verify.py

This pull-request removes the string concatenation in `etherscan_verify.py` and instead uses `join-contracts.py`.  This closes #525.
Some refactoring will follow (now possible because this PR removes contract-specific code).
Even after this change, Etherscan verification timeouts: https://github.com/raiden-network/raiden-contracts/issues/530 but at least I added an error message explaining how to get the source verified in a web browser.

Use join-contracts.py script for Etherscan verification

---

README.rst
raiden_contracts/deploy/etherscan_verify.py

Please review #532 first.
This PR extends
After testing this on Ropsten, I can close
https://github.com/raiden-network/raiden-contracts/issues/484 .

extend etherscan-verify.py to cover the service contracts

---

README.rst
raiden_contracts/deploy/etherscan_verify.py

This commit
* fixes the exit status code when Etherscan submission fails
* changes README so it instructs just one etherscan_verify execution
@karlb  Here comes the change promised in https://github.com/raiden-network/raiden-contracts/pull/533#discussion_r254709542

All Etherscan verification at once

---

.bumpversion_contracts.cfg

This issue fixes the `bumpversion` configuration for service contracts.  See #551 for the problem description.
0.10.0 release is blocked for this PR now.

Fix bumpversion_contracts.cfg for service contract

---

README.rst

This PR gives more detailed explanations of different `contract_version`s.
[skip ci]

Improve explanations of contract versions

---

README.rst
raiden_contracts/deploy/etherscan_verify.py

As suggested in https://github.com/raiden-network/raiden-contracts/pull/345#discussion_r231039624.
This closes https://github.com/raiden-network/raiden-contracts/issues/349 .

pprint posted data to etherscan

---

Makefile
raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/tests/test_contracts_compilation.py
raiden_contracts/utils/join-contracts.py
raiden_contracts/utils/logs.py
raiden_contracts/utils/private_key.py
requirements-dev.txt

Mypy will just assume `Any` for all types, but that still allows to
catch errors because types will be inferred from signatures in other
places.

Enable mypy for functions without type declaration

---

raiden_contracts/tests/test_deploy_script.py

This PR extends `test_deploy_script` to cover the function `deploy_service_contracts()`  This closes #450.

Test service deploy script

---

README.rst

A user of `raiden-contracts` package sees at least four different version numbers.  So I'm asked to add an explanation:  https://github.com/raiden-network/raiden-contracts/issues/584#issuecomment-465130743
[skip ci]

Add FAQ with version number related questions

---

README.rst
raiden_contracts/tests/test_contracts_compilation.py

Now I'm documenting what's happening right now.  Maybe is it reasonable to provide deployment information of all contract versions?
[skip ci]

README only three contract_versions are available

---

raiden_contracts/contracts/raiden/TokenNetwork.sol

This PR spawns out of https://github.com/raiden-network/raiden-contracts/issues/598 .  Now we noticed that the result of `getChannelInfo()` can be gamed.  This PR adds a comment explaining that.
[skip ci]

Comment, cannot distinguish Settled and Removed

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

into two functions.
Sometimes deployment_data was given, and sometimes
it was not given. Different usage shared some execution path but
didn't do the same thing.
This commit separates these two functionalities into two different
functions.

Separate two usages of verify_deployed_contracts()

---

CHANGELOG.md
README.rst
raiden_contracts/contract_manager.py
raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/fixtures/base/contract_manager.py
raiden_contracts/tests/fixtures/base/utils.py
raiden_contracts/tests/test_contracts_compilation.py
setup.py

For #599, `raiden-contracts` needs to provide both `limited` and `unlimited` deployment data.  This PR computes the directory names for these flavors.  This changes the ABI.  See the diff of Changelog.

Consider flavors (Limited or Unlimited) to find directories

---

raiden_contracts/tests/fixtures/token_network_registry.py

14451796913a2942e00f13fa9fcf1404c3a200ce

Remove unused `token_network` argument introduced in

---

raiden_contracts/tests/fixtures/base/address.py
raiden_contracts/tests/fixtures/base/contract_manager.py
raiden_contracts/tests/fixtures/base/utils.py
raiden_contracts/tests/fixtures/base/web3_fixtures.py
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/tests/fixtures/monitoring_service.py
raiden_contracts/tests/fixtures/one_to_n.py
raiden_contracts/tests/fixtures/secret_registry.py
raiden_contracts/tests/fixtures/service_registry_fixtures.py
raiden_contracts/tests/fixtures/token.py
raiden_contracts/tests/fixtures/token_network_fixtures.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/fixtures/user_deposit.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py
raiden_contracts/tests/utils/__init__.py
raiden_contracts/tests/utils/address.py
raiden_contracts/tests/utils/constants.py

This only reduces the runtime by ~25%, but further speed increases can be gained by updating the scope of more fixtures.
I've also tried to reduce the number of fixtures to keep the test setup complexity down a bit. See the single commit messages for more details.

Allow fixtures to be reused across multiple tests

---

raiden_contracts/tests/test_channel_settle_unlock_state.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_deploy_script.py

This allows skipping tests with `pytest -m 'not slow'`. Now, I can get a
run of all non-slow tests down to 90s in my machine (also using `-n 4`).

Mark slow tests

---

raiden_contracts/tests/test_token_network_registry.py

test_create_erc20_token_network_call().
This closes #654.

Test invalid deposit limits in

---

raiden_contracts/tests/test_token_network.py

test_token_network.py
This closes
https://github.com/raiden-network/raiden-contracts/issues/656

Test invalid limits in test_constructor_call in

---

raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/test_print_gas.py

Before this commit, parallel execution of test_print_gas.py left corrupt
gas.json file because the last writer overwrote the other writers' data.
After this commit, test_print_gas.py contains only one test, so gas.json
is not corrupted this way.

Gather all gas printing tests into one

---

raiden_contracts/tests/test_priv_key.py

This should improve the test coverage, and possibly Codecov stops complaining about #669.

Test some error cases in utils.private_key

---

MANIFEST.in

Before this commit, `raiden-contracts` source package did not contain the changelog.  This commit fixes that problem.
[skip ci]

Not Changelog but CHANGELOG

---

CHANGELOG.md
README.rst
RELEASE.rst
raiden_contracts/contract_manager.py
raiden_contracts/data/contracts.json
raiden_contracts/tests/test_contracts_compilation.py

into the current contracts version.
During the release process, the version number in contracts.json will be changed by hand.

Stop automatically converting version=None

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/test_transaction.py
raiden_contracts/utils/transaction.py

The function `raiden_contracts.utils.check_successful_tx` had no unit tests.  I'm adding them.

Test check_successful_tx

---

raiden_contracts/tests/test_channel_settle.py

Because in this case, both participants should get the original deposits back.

Check final balances in test_settle_no_bp_success

---

raiden_contracts/contract_manager.py

Flavors ("limited" and "unlimited") were used for a few days but are no longer used.  This PR removes some leftover mentions of the flavors.
This closes #694.

Remove the word flavor from docstrings

---

raiden_contracts/contract_manager.py
raiden_contracts/contract_source_manager.py
raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/fixtures/base/contract_manager.py
raiden_contracts/tests/test_contracts_compilation.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_etherscan_verify.py
raiden_contracts/tests/test_print_gas.py
setup.py

Before this PR, there were two ways to create a ContractManager object, with sources and with precompiled json file.  This PR splits the two uses into two different classes.
This closes #695.

Split ContractSourceManager from ContractManager

---

raiden_contracts/utils/logs.py

CodeClimate says wait() is too complicated (#717). This commit tries to
simplify the method.

Simplify LogHander.wait()

---

raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/test_print_gas.py

CodeClimate says etherscan_verify() is too complicated (#716).
This commit is trying to simplify the function.

Simplify etherscan_verify

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

Since a new argument was added to the constructor of TokenNetworkRegistry, the deployment script did not work for older contract versions without the new argument.  This PR fixes that problem.
Closes #731.

Deployment script now works with 0.3._ again

---

raiden_contracts/tests/fixtures/base/web3_fixtures.py
raiden_contracts/tests/utils/constants.py
raiden_contracts/tests/utils/contracts.py

* `tests.utils.constants` is a better place from them
* some could be deleted
* avoids a circular import

Move test constants from `web3_fixtures.py`

---

.travis.yml
raiden_contracts/tests/test_contracts_compilation.py
raiden_contracts/tests/test_deploy_script.py

Running test_deploy_script took 142 seconds before this commit but now 64 seconds.
This closes #736.

Quicker test_deployment_script

---

raiden_contracts/utils/logs.py

CodeClimate says handle_log is too complicated #715.
This commit tries to make the function simpler.
I saw some numbered index access `[0]` and `[1]` that could be named.  So I introduced a named tuple.

Simplify handle_log

---

raiden_contracts/utils/logs.py

By @palango 's [suggestion](https://github.com/raiden-network/raiden-contracts/pull/727#discussion_r267276318), I moved a type definition upwards in a file.

Move a type definition upwards

---

raiden_contracts/utils/join-contracts.py

because CodeClimate says it is too complicated:
https://github.com/raiden-network/raiden-contracts/issues/763

Split a complicated function `join()`

---

raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/deploy/contract_verifyer.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/logs.py

This PR purely shuffles code around.
The original motivation was to reduce the number of lines in `raiden_contracts/deployer/_main_.py` 
https://github.com/raiden-network/raiden-contracts/issues/714 .
* I moved some code from `_main_.py` into `contract_deployer.py`.
* Then I had to separate `contract_verifyer.py` away because sometimes we don't have enough information to deploy but just want to verify the existing deployement data.

Split verifyer away from deployer

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

Before this PR, `deploy register` command always failed.
There was a check against an obsolete option `--registry-address` and the check
was always called and failed.
Fixes #766

Make deploy register runnable

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/test_deploy_script.py
requirements.txt

`deploy register` failed on contracts version 0.4.0.  This commit fixes
#769

Make 0.4.0 deployable again

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

When `deploy register` fails for the obsolete option `--registry-option`
the script should make a suggestion to use `--token-network-registry`.
This fixes #765.

Make a suggestion when failing for obsolete option

---

CHANGELOG.md
README.rst
raiden_contracts/contract_manager.py
raiden_contracts/deploy/contract_verifyer.py
raiden_contracts/tests/test_deploy_data.py
requirements.txt

`get_contracts_deployed()` had two problems
* you had to call it twice to get all deployment data #774 
* the name sounded like the function deploys contracts, but it doesn't #671 
This PR fixes both by introducing a new interface function `get_contracts_deployment_info()` that takes `module: str` instead of `services: bool`.  Moreover, `module` defaults to `all`, meaning "give me deployment info for all modules".
Also `get_contracts_deployed()` is deprecated.

get_contract_deployment_info that returns both service and raiden deployment info by default

---

requirements.txt

because the script contains
```
from mypy_extensions import TypedDict
```
This fixes #778.  This should be trigger a release.

The deployment script requires mypy_extensions

---

requirements.txt

because we use `hidden` options.
This commit fixes https://github.com/raiden-network/raiden-contracts/issues/784

click must be at least 7.0

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

There was a bug when the deployment script tried to see whether
0.3._ requires deposit limits, the script tried to interpret
'0.3._' as a semver but failed becaue '0.3._' is not a semver string.
This fixes https://github.com/raiden-network/raiden-contracts/issues/787

Enable 0.3._ TokenNetwork creation

---

raiden_contracts/constants.py
raiden_contracts/contract_manager.py
raiden_contracts/tests/test_deploy_data.py

Without doing this, I was unable to call `get_contracts_deployment_info()` from `contract_verifyer.py`.
I saw an error:
```
if module not in DeploymentModule:
>           raise ValueError(f'Unknown module {module} given to get_contracts_deployment_info()')
E           ValueError: Unknown module DeploymentModule.RAIDEN given to get_contracts_deployment_info()
```
from `get_contracts_deployment_info()`.
It seemed like the Enum visible locally in contract_manager.py was different from the Enum imported into contract_verifyer.py .
I guess that's why many enums are defined in `constants.py`.`

Move DeployedModule enum to constants.py

---

raiden_contracts/contract_manager.py
raiden_contracts/tests/test_deploy_data.py

and older deploymen data.
This is a part of https://github.com/raiden-network/raiden-contracts/issues/807

Don't try to find service contracts for RedEyes

---

setup.py

When other packages import raiden-contracts, the type signatures will
not be used by mypy unless the package declares itself as properly
types.  This can be done via PEP561:
https://mypy.readthedocs.io/en/latest/installed_packages.html#using-pep-561-compatible-packages-with-mypy
Adding this will improve type checking quality in raiden-services (and
potential other packages) whenever imports from raiden-contracts are
used.

Declare raiden-contracts to be typed via PEP561

---

.bumpversion.cfg
CHANGELOG.md
setup.py

because #813 exposes the type-checking information to `raiden` and `raiden-services`, the CI in `raiden` and `raiden-services` might get additional mypy errors.  This release is for finding them sooner.

0.17.2 release

---

RELEASE.rst

Update the changelog before actually bump the version.
This closes #625.
[skip ci]

Reorder release process

---

raiden_contracts/contract_manager.py
raiden_contracts/contract_source_manager.py
raiden_contracts/deploy/contract_verifyer.py
raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_etherscan_verify.py
requirements.txt

As far as I know, neither `raiden` or `raiden-services` uses `get_contracts_deployed()` interface anymore.  This PR removes the function from `raiden-contracts` codebase.

Remove get_contracts_deployed()

---

raiden_contracts/deploy/contract_verifyer.py

This commit tells which block number comes from where, so the failure
becomes easier to debug.
Fixes #796.

Better assertion failure for wrong block number

---

raiden_contracts/tests/test_transaction.py
raiden_contracts/utils/transaction.py

and when a transaction receipt does not contain 'status' field.
It's sometimes hard to connect a missing 'status' and the Byzantium hard fork.

Show a better error message before Byzantium

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/test_deploy_script.py

because most of the parameter-passing and error-checking was
already implemented in CotnractDeployer.transact().
This implements the idea and closes https://github.com/raiden-network/raiden-contracts/issues/515

Refactor register_token_network()

---

raiden_contracts/tests/fixtures/base/utils.py

in the command line argument 'test_print_gas'.
For historical reasons one test case prints the gas consumption in
gas.json.  There is another test that checks the integrity of gas.json
but it fails when the two tests run in parallel.
This fixes https://github.com/raiden-network/raiden-contracts/issues/839
As a solution, this commit disables the writing unless the
command line argument contains 'test_print_gas'.

Do not change gas.json unless explicitly told

---

.bumpversion.cfg
CHANGELOG.md
setup.py

Mainly to expose the Görli deployment information.

0.18.0 Release

---

raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/test_deploy_script.py

talking to a TokenNetworkRegistor contract is quite similar to
deploying a contract. ContractDeployer is the natural place for
register_token_network() for now.

Move register_token_network into ContractDeployer

---

raiden_contracts/tests/fixtures/channel.py

In a test, a path was never taken because of a typo.  This commit
fixes that.
This closes #810

Fix a typo that made deadcode

---

raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/utils/versions.py

Here and there I saw ad-hoc functions for deciding which
contracts_version expects which options.
This commit gathers these functions into a new module.
This makes CodeClimate happier https://github.com/raiden-network/raiden-contracts/issues/704

"Which version takes which options" into a module

---

CHANGELOG.md
raiden_contracts/contract_manager.py
raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/unit/test_files.py

when the deployment file is not found.  This closes https://github.com/raiden-network/raiden-contracts/issues/860

get_contracts_deployment_info() returns None instead of raising a ValueError

---

raiden_contracts/deploy/contract_deployer.py

Split `register_token_network()` into two functions for deploying a TokenNetwork with deposit limits, and another function for deploying a TokenNetwork without deposit limits.
The original function contained lots of
```
if with_limits:
...
else:
...
```
I guess that caused CodeClimate to complain about the complexity of `register_token_network()` function.

Split two cases with_limits and without_limits

---

raiden_contracts/deploy/etherscan_verify.py

Comparing a string against a string literal with 'is' looks wrong,
said pylint.

Remove a wrong 'is' usage

---

.travis.yml
requirements-dev.txt
requirements.txt

So that when pip installs incompatible packages, the CI builds fail.
Closes #882.

Use pipdeptree to detect inconsistent dependencies

---

raiden_contracts/contract_manager.py
raiden_contracts/deploy/etherscan_verify.py

These three lines were in etherscan_verify.py but they belong to
ContractManager in terms of functionality.
This commit closes #871.

A new method get_constructor_argument_types()

---

raiden_contracts/tests/deprecation_switch_testnet.py

so that the code duplication is reduced.
This closes #872.

Use deployer.transact() in one more place

---

raiden_contracts/deploy/contract_verifier.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_deploy_script.py

because this function took a boolean and did two completely different things depending on the boolean.

Split store_and_verify_deployment_info_services()

---

.pylint.rc
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_settle_unlock_state.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_deprecation_switch.py
raiden_contracts/tests/utils/channel.py

This hit ChannelValues class so I introduced LockedAmounts that
combined three attributes of ChannelValues.

Enable pylint against too many instance attributes

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

This is a leftover of #896.  Some function signatures changed there
but not all calling sites were updated accordingly.
I expect a Codecov error right now.  I need to write tests to cover those cases.

Fix how to call verify_contracts_deployment_data

---

raiden_contracts/deploy/__main__.py

Fix the keyword argument's key

---

raiden_contracts/tests/conftest.py
raiden_contracts/tests/test_channel_settle_unlock_state.py
requirements-dev.txt

This PR upgrades flake8 to the version that's used in `raiden`.  Also this PR removes string comparison with `is`, so avoiding the wtfpython world.

Update flake8 and fix string comparison

---

raiden_contracts/deploy/contract_verifier.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/tests/utils/constants.py

Previously it was very difficult to test those failure cases where
a contract's address stored in another contract's storage is wrong.
For that I would need to mock the contract's function calls, and that's
somewhere deep inside web3.py.
Instead, I chose to split away those checks in smaller functions
so I can write tests on these checks separately, with more precise
control over which assertion should fail.
This is a prerequisite for #921. There, since tests are hard to write,
I couldn't calm down CodeCov.

Split subroutines away from verify_service_contracts_deployment()

---

requirements-dev.txt
requirements.txt

because having eth-abi<=1.2.2 in requirements.txt caused
an undesirable downgrade in `raiden` package.
https://github.com/raiden-network/raiden/pull/4043#issuecomment-492248307
By the way, if I simply remove `eth-abi<=1.2.2` from both files, I get
```
ERROR: eth-abi 1.3.0 has requirement eth-typing<3.0.0,>=2.0.0, but you'll have eth-typing 1.3.0 which is incompatible.
```
during `pip install -r requirements-dev.txt`.
The cause and effects follow like this:
* web3 4.9.1 requires eth-tester[py-evm]==0.1.0-beta.33
* eth-tester 0.1.0-beta.33 requires py-evm==0.2.0a33
* py-evm 0.2.0a33 requires eth-typing<2.0.0,>=1.1.0
* `eth-typing 1.3.0` is too new for `eth-abi 1.3.0`.

Move eth-abi<=1.2.2 into requirements-dev.txt

---

.bumpversion.cfg
CHANGELOG.md
setup.py

When this is merged, the plan is to make a PyPI release 0.19.1, and then create a replacement for https://github.com/raiden-network/raiden/pull/4043 .

Release 0.19.1

---

README.rst

README contained a line `make render_contracts`. This does not
work anymore.  The line is a leftover from the time we tried
Mustache.

Remove render_contracts that no longer exists

---

.bumpversion_contracts.cfg

Since we introduced black, we are using double quotes.
This fixes https://github.com/raiden-network/raiden-contracts/issues/983

Use double quote in bumpversion template

---

raiden_contracts/contract_manager.py
raiden_contracts/tests/test_contracts_compilation.py

The new check makes sure that
`assert self.contracts` in `get_contract()` never fails.

Check whether the contracts field is None

---

CHANGELOG.md
README.rst
raiden_contracts/contract_manager.py
raiden_contracts/tests/test_print_gas.py

This PR adds an API `gas_measurements(contracts_version)` that exposes the gas measurements as a dictionary.

Expose the gas measurements

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/fixtures/base/web3_fixtures.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/test_channel_cooperative_settle.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py
raiden_contracts/tests/utils/channel.py
raiden_contracts/tests/utils/contracts.py
raiden_contracts/utils/proofs.py

This commit is mostly type annotations.  There is one change that affects the runtime behavior.  Somehow `bytes` were converted into `str` when there was no need to.
This is a part of #918.

More type annotations and a small fix

---

raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_settle_unlock_state.py
raiden_contracts/tests/test_channel_unlock.py
raiden_contracts/tests/test_deprecation_switch.py
raiden_contracts/utils/pending_transfers.py

because the function had many optional arguments and had
essentially two separate usage patterns.
This fixes #1002.

Separate get_pending_transfers_tree() into two

---

raiden_contracts/contract_manager.py
raiden_contracts/tests/unit/test_merge_dict.py

merge_deployment_data() might get two dictionaries that have the
same keys.

Replace an assert that might fail

---

raiden_contracts/tests/utils/channel.py

I saw a function `are_balance_proofs_valid()` and it seemed some conditions are missing.

More conditions for valid balance proofs

---

raiden_contracts/contract_manager.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/utils/versions.py

and somehow util modules should not depend on contract_manager.
This fixes #1009.

Move a small function to util/versions.py

---

raiden_contracts/tests/fixtures/channel_test_values.py
raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_withdraw.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/utils/address.py
raiden_contracts/tests/utils/channel.py
raiden_contracts/tests/utils/constants.py

because it's called that way in `raiden` repo.

Rename MAX_UINT256 into UINT256_MAX

---

raiden_contracts/tests/unit/test_recover_from_signature.py
raiden_contracts/utils/proofs.py
raiden_contracts/utils/signature.py

This PR replaces asserts in `sign()` with `if not ...: raise ...`.  Sometimes `assert` is omitted in an optimised execution, but input checks should be always performed.
This PR is a part of #847.
I expect a CodeCov failure, and then I'll add tests to cover the new paths.

Replace asserts in sign()

---

Makefile

because it removes unused imports.

Run autopep8 in make format

---

.travis.yml
Makefile

Rather than making lint dependent on mypy, I just moved the contents
of `make mypy` task into `make lint`. Usually linting should run
before mypy runs.
This closes #911.

Combine make lint and make mypy

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/versions.py

Since this version is about a combination of contracts,
I chose to use contracts_version everywhere, and never
contract_version.
This fixes #1007.

contract_version -> contracts_version

---

README.rst
raiden_contracts/contract_manager.py
raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/deploy/contract_verifier.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/tests/unit/test_files.py
raiden_contracts/utils/file_ops.py

This PR implements the feature of reusing SecretRegistry form a previous deployment file.
After this PR, users are able to use the same SecretRegistry instance for multiple deployments of TokenNetworkRegistrys.  Then a payment spanning the multiple TokenNetworks become possible.
This fixes #963 .

Reusing SecretRegistry from a previous deployment file

---

raiden_contracts/deploy/contract_verifier.py
raiden_contracts/tests/test_deploy_script.py

because assertions can be omitted by optimizations.

Checking constructor args should not be assert

---

raiden_contracts/constants.py
raiden_contracts/tests/test_monitoring_service.py
raiden_contracts/tests/utils/channel.py
raiden_contracts/tests/utils/constants.py

because the constant is useful in `raiden` codebase.

Move LOCKSROOT_OF_NO_LOCKS out of tests module

---

Makefile
setup.cfg

This allows running mypy without any arguments, which makes more tooling
work out of the box.
`--check-untyped-defs` is not needed anymore, since untyped defs are disallowed.

Make mypy read all config from `setup.cfg`

---

raiden_contracts/tests/unit/test_recover_from_signature.py
raiden_contracts/utils/proofs.py

The packing functions can be reused with the client's `Signer` objects,
which do their own hashing.
See #1041
I've prepare https://github.com/raiden-network/raiden/pull/4423 to update the raiden client to use these functions.

 Use `pack_*` instead of `hash_*` proof functions

---

raiden_contracts/tests/test_service_registry.py

Such an attempt fails because then the price is dumped instead of being bumped.

Add a test that sets the bump numerator to zero

---

raiden_contracts/tests/test_service_registry.py

This PR adds a test that sets a very small decay constant of ServiceRegistry.  Then the price decays very quickly.

Test a very small decay constant

---

raiden_contracts/tests/test_service_registry.py

The test uses the biggest allowed decay constant to see how the price decaying function behaves.

Add a test about a very big decay constant

---

Makefile
RELEASE.rst

I was using `make update_gas_costs` and noticed that
* the feature was not documented in the release document
* it executed two tests instead of one.
So this PR fixes these points.

Document `make update_gas_costs`

---

raiden_contracts/tests/test_service_registry.py

This PR adds a test that changes the bump denominator of ServiceRegistry to zero.  Such a change fails with a specific error message.

Test changing the bump denominator to zero

---

raiden_contracts/tests/test_service_registry.py

not because the amount is not enough.
Before this PR, it was unclear why the deposit transaction fails.

Make sure deposit fails for deprecation switch

---

raiden_contracts/tests/test_channel_deposit.py
raiden_contracts/tests/test_channel_open.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py
raiden_contracts/tests/utils/constants.py

Before this commit, a string FAKE_ADDRESS was sometimes used
as a random address and sometimes as an oddly-sized string
that's not an address.  The real value of FAKE_ADDRESS was
an oddly-sized string that's not an address.
This commit separates this constant into two: FAKE_ADDRESS and
NOT_ADDRESS. FAKE_ADDRESS is a random address while NOT_ADDRESS
is an oddly-sized string that's not an address.
This closes #1166.

Separate FAKE_ADDRESS and NOT_ADDRESS

---

raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/utils/join_contracts.py

This commit replaces a dash with an underscore in a name of a Python source file.
It seems [1] Python sources should not be named with a dash, but
an underscore is tolerated.  
[1] http://google.github.io/styleguide/pyguide.html#316-naming
I tried to make sure that all documents etc contain the new name instead of the old name.
----
* Bookkeep

Use _ instead of - in a file name

---

raiden_contracts/tests/test_service_registry.py

function from out of the contract.
This commit is a part of solving #581.

Test calling the internal setDecayConstant()

---

raiden_contracts/tests/test_service_registry.py

from out of the contract.
This commit is a part of #581.

Test calling an internal setPriceBumpParameters()

---

CHANGELOG.md
raiden_contracts/tests/test_contract_joiner.py
raiden_contracts/utils/join_contracts.py

`join-contracts.py` raises an exception when a file does not exist.
Before this commit, join-contracts.py silently skipped
non existing files.  The result is usually not useful
and might lead to nonpleasant surprises.
This closes #522.
none.
----
* Bookkeep

Complain when file does not exist

---

raiden_contracts/tests/test_service_registry.py

directly from out of the contract.
This commit is a part of solving #581.

Test calling internal setMinPrice() function

---

raiden_contracts/deploy/contract_verifier.py

This fixes #1170.
Adds a space between two words.
The error message spans over multiple lines in the source code.
There was a missing space at the end of a line so the last word
"receipt" and the first word on the next line "from" collapsed
together into one word "receiptfrom".
Nothing.
----
* Bookkeep

Add a missing space

---

raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/test_deploy_script.py

Changes the deploy script to allow for configurable settlement timeouts
The smart contracts deployed for the testnets have a settle timeout that is too high.
----
* Bookkeep

deploy script with configurable settle timeouts

---

raiden_contracts/tests/fixtures/test_contracts.py

This PR changes the type of an argument called `custom_token` from `Web3` to `Contract`.
I was looking at the file for something else and noticed that the type is wrong.
Why mypy didn't catch this? Probably it doesn't understand how pytest fixtures are found.
----
* Bookkeep

Fix type annotation custom_token is a Contract

---

CHANGELOG.md

Fixes so the 0.32.0 Changelog link directs to contracts release v0.32.0 instead of v0.31.0
0.32.0 Changelog links to contracts release v0.31.0
-
----
* Bookkeep

fix Changelog link for v0.32.0 release

---

raiden_contracts/contract_source_manager.py
requirements-dev.txt

I don't know why but the word Parmas sounded delicious.
In fact it was about Params or parameters.
This PR replaces a comment "Parmas" with "Params".
I was looking at the file blankly when I saw the typo.
Nothing.
----
* Bookkeep

Fix a typo "Parmas"

---

raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/test_etherscan_verify.py
requirements-dev.txt

This PR modifies etherscan_verify so it raises an error on an unknown contract name.
Before this PR the script silently succeeded while not doing anything.  This can be confusing when a user makes a typo.
Nothing.
----
* Bookkeep

Error on unknown contract names

---

CHANGELOG.md
raiden_contracts/contract_source_manager.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/tests/test_contracts_compilation.py
setup.py

This PR makes ContractSourceManager's constructor compute the checksums.  Before this PR, users had to initialize the object by calling `compute_checksums()` before calling some other methods.
It's nicer when users don't need to care about the internal states of the class.
I made sure that once initialized `contracts_checksums` and `overall_checksum` do not change.
----
* Bookkeep

Constructor computes checksums (so users don't need to initialize the object)

---

raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/tests/fixtures/deposit_fixtures.py
raiden_contracts/tests/fixtures/monitoring_service.py
raiden_contracts/tests/fixtures/one_to_n.py
raiden_contracts/tests/fixtures/service_registry_fixtures.py
raiden_contracts/tests/fixtures/test_contracts.py
raiden_contracts/tests/fixtures/token.py
raiden_contracts/tests/fixtures/token_network_fixtures.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/fixtures/user_deposit.py
raiden_contracts/tests/test_contract_limits.py
raiden_contracts/tests/test_deprecation_switch.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_service_registry.py
raiden_contracts/tests/test_token_network.py
raiden_contracts/tests/test_token_network_registry.py
raiden_contracts/tests/utils/channel.py
setup.cfg

This fixes #1210.
This commit forces these arguments to be provided as kwargs.
Some smart contracts' constructors take many arguments,
so it's easy to mistake an argument for another.
Nothing.
----
* Bookkeep

Deploy contracts with kwargs

---

RELEASE.rst
pull_request_template.md

This fixes #1218.
This PR describes what to do with additional `require()`s.
Because in many occasions, new `require()` was added but
that was not reflected in the smart contract proxies in
the Raiden node codebase.
Nothing.
----
* Bookkeep

Add entries in checklist on require() and assert()

---

raiden_contracts/contract_manager.py
requirements-dev.txt

that was never needed.
This fixes https://github.com/raiden-network/raiden-contracts/issues/1262
This PR removes two lines that initialized variables with `None`.
I saw somewhere else `mypy` complain that these variables might be `None`. (When I was implementing https://github.com/raiden-network/raiden-contracts/issues/1257).
Nothing.
----
* Bookkeep

Remove None initialization

---

Makefile
raiden_contracts/tests/test_channel_update_transfer.py

Before this comment, `make format` showed
```
[Errno 21] Is a directory: 'raiden_contracts/'
```
This commit fixes the command.
`autopep8` needed `--in-place --recursive` options.
This closes https://github.com/raiden-network/raiden-contracts/issues/1165
This PR changes `Makefile`. `autopep8` command now gets `--in-place --recursive` options.
Before the PR, `make format` showed an error from `autopep8`.
Nothing.
----
* Bookkeep

Fix autopep8 command

---

raiden_contracts/tests/unit/test_recover_from_signature.py
setup.cfg

This PR copies `mypy` configuration from `raiden` repository.
It's better to use the same configurations in `raiden` repo and here.
Nothing.
----
* Bookkeep

Copy mypy configs from `raiden`

---

raiden_contracts/tests/test_service_registry.py

fails. This closes https://github.com/raiden-network/raiden-contracts/issues/581
This PR adds a test about deploying a ServiceRegistry on a token with zero total supply.
I came up with this test case when I was drafting https://github.com/raiden-network/raiden-contracts/issues/581 .  This is the last remaining test case in that issue.
I copied and pasted many constructor arguments from a test below.  Perhaps that's a bad practice.
----
* Bookkeep

Test ServiceRegistry deployment with zero supply token

---

raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py

Before this commit, if the user specifies `--gas-price 0`, that
caused the Ethereum node to choose the gas price.  That was
counterintuitive, and this feature was not documented.
This commit removes this possibility.
This fixes #1284.
This commit removes
* the undocumented feature of `ContractDeployer` that lets the Ethereum node choose the gas price, when 0 was specified as the gas price.
* the default gas price value in `ContractDeployer`.
These features were not documented and were never used. The scripts should just fail in these weird cases rather than try to find something reasonable on its own.
Nothing.
----
* Bookkeep
* …

Simplify gas price logic

---

raiden_contracts/tests/test_channel_close.py

This fixes #1271.
Turn all calls of `check_channel_closed()` into kwarg calls.
kwargs are easier to understand.
Nothing.
----
* Bookkeep

Call check_channel_closed with kwargs

---

MANIFEST.in

This PR adds one line in MANIFEST.in
I saw a file missing in the PyPI package
It was a bit tricky to figuring out why the file was missing.
----
* Bookkeep

Include new file in MANIFEST

---

raiden_contracts/tests/test_service_registry.py

so there have to be two tests.
This fixes #1268.
This PR copies a test into two. The test was failing for a wrong reason.
The first copy is renamed so it shows why it fails (because ServiceRegistry has no code).
The second copy is edited so that it fails for the originally intended reason. In the second copy I added the `match="..."` so the reason of the failure is clearer.
Because the test was failing for a wrong reason #1268.
Nothing.
----
* Bookkeep
And before "merge" all …

Withdraw fails for empty contract or too early try

---

raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_channel_close.py
raiden_contracts/tests/test_channel_settle.py
raiden_contracts/tests/test_channel_update_transfer.py
raiden_contracts/tests/test_monitoring_service.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/unit/test_recover_from_signature.py
raiden_contracts/tests/unit/test_unit_signatures.py
raiden_contracts/tests/utils/constants.py

This PR changes `create_balance_proof()`s return value from a tuple to a dictionary.
* accessing tuple elements like `balance_proof[0]` `balance_proof[3]` was less readable than `balance_proof["balance_hash"]`.
* in order to use `**balance_proof` in other function calls, `balance_proof` has to be a dictionary.
The fields of the dictionary have the same name as the parameters of `create_balance_proof_countersignature()`.
----
* Bookkeep

Balance proof as a namedtuple instead of a tuple

---

raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/versions.py

This fixes #1168.
This PR makes `click` complain when `--token-network-registry-address` is missing in the service contract deployment command.
When --token-network-registry-address was missing, the
deployment script showed a mysterious error
```
TypeError: One or more arguments could not be encoded to the necessary ABI type.  Expected types are: address, address, address, address
```
Older service contracts didn't need this value. The script didn't work for these old versions.  So I made the script complain explicitly when the user wants to deploy these older versions.
----
And before "merge" all checkboxes have to be checked.  If you find redundant …

Better error message for missing command argument

---

.bumpversion_contracts.cfg
RELEASE.rst

as proposed in https://github.com/raiden-network/raiden-contracts/issues/584#issuecomment-544935108
This PR
* modifies `RELEASE.md` so it describes the new versioning scheme
* removes a `bumpversion` configuration that won't be used.
Having two distant version numbers is confusing.  Some people are totally confused about the version numbers.  Some others deny that the current scheme is too hard for human beings, but I've seen enough confusion.
We are here slightly abusing `semver` because after this PR, `minor` means "contract changes" and `patch` means "Python script changes".
As far as we are in `0.x.y` range, the Semantic Versioning permits anything at any moment.
----
And before "merge" all checkboxes have to be checked.  If you find redundant points, …

Change the versioning scheme for contracts_version

---

CHANGELOG.md
raiden_contracts/contract_source_manager.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/fixtures/base/contract_manager.py
raiden_contracts/tests/test_contracts_compilation.py
setup.py

This fixes #1312.
* After this PR, the bytecode verification on `CONTRACTS_VERSION` happens against the right source from `data_CONTRACTS_VERSION`, not from `data`.
* `contracts_source_path()` takes a new argument `contracts_version`.
Currently, it's impossible to deploy Raiden contracts on a private network so people can test `raiden` #1312.
Nothing.
I've tested that this PR fixes the problem I saw in #1312.
----

Fix the source code check on CONTRACTS_VERSION

---

.bumpversion.cfg
CHANGELOG.md
setup.py

This PR bumps the package version to 0.33.3.
* to pass on the bug fix in #1313 to the downstream.
Nothing.
----

Release 0.33.3

---

CHANGELOG.md
Makefile
README.rst

This PR introduces a new `Makefile` goal `make install-dev`.
Other repos `raiden` and `raiden-services` have it, and I think it's a good idea.
I updated `.PHONY` variable in the Makefile.
----

`make install-dev`

---

README.rst

`get_contracts_deployment_info` was used below,
but the name was not imported anywhere.
This fixes #1294.
----

Add an import in README code sample

---

raiden_contracts/deploy/contract_deployer.py

This fixes #1060.
Replaces some `str` with `HexAddress`.
`HexAddress` is a more precise type annotation.
Nothing.
----

Addresses are at least HexAddress not just str

---

raiden_contracts/deploy/contract_verifier.py

`indent=4` enables the pretty printing of dumps.
This closes #1293.
----

Pretty print deployment json files

---

raiden_contracts/contract_source_manager.py
raiden_contracts/tests/test_contracts_compilation.py
raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/versions.py

This commit separates a function that checks one entry of
contracts.json.  This eases the implementation of #1257.
This is a pure refactoring that separates away a subroutine.
Before this PR, ContractSourceManager didn't have a function that checks a single entry of `contracrts.json`.  There was only `verify_precompiled_checksums()` that checks all entries of `contracts.json`.  This PR separates `_verify_single_precompiled_checksum()` that checks a single entry of `contracts.json`.
After this PR, I want to expose a feature to check a single `contracts.json` entry.  That will be useful for [checking whether or not SecretRegistry's sources have changed](https://github.com/raiden-network/raiden-contracts/issues/1208#issuecomment-537490029).
I had to take a moment to name the arguments of the …

Separate _verify_single_precompiled_checksum()

---

raiden_contracts/tests/test_monitoring_service.py

This commit adds a test that calls the MonitoringService's
constructor with a service registry address that has not code.
This is supposed to cause a failure in one of the require()
sentences in the constructor.
This test is a part of https://github.com/raiden-network/raiden-contracts/issues/572
Nothing.
----

Test MS constructor with ServiceRegistry without code

---

raiden_contracts/tests/test_monitoring_service.py

address without code.
This is a part of testing failure cases in MonitoringService https://github.com/raiden-network/raiden-contracts/issues/572 .
Nothing.
----

Test MonitoringService deployment with token address without code

---

raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/tests/fixtures/service_registry_fixtures.py
raiden_contracts/tests/fixtures/token_network_fixtures.py
raiden_contracts/tests/fixtures/token_network_registry.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/test_service_registry.py
raiden_contracts/tests/test_token_network_registry.py
raiden_contracts/tests/utils/constants.py

This fixes https://github.com/raiden-network/raiden-contracts/issues/1183
Renames CONTRACT_DEPLOYER_ADDRESS into DEPLOYER_ADDRESS
because CONTRACT_* are usually names of contracts.
This is only used in tests, so will not affect other packages.
----

CONTRACT_DEPLOYER_ADDRESS into DEPLOYER_ADDRESS

---

raiden_contracts/tests/test_deploy_data.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/versions.py
requirements-dev.txt

* This PR forces pip to install newer versions of `black`.
* This PR formats Python sources using a new version of `black`.
I saw a build failure on `master`
https://travis-ci.org/raiden-network/raiden-contracts/builds/604348795?utm_medium=notification&utm_source=email
This happened when the CI used a newer version of black.
Since our codebase should not ban newer versions of black, this codebase has to embrase the newer versions of black.
Nothing.
----

Format with newer black (fixes master build failure)

---

raiden_contracts/deploy/__main__.py

Simplifies the signatures of some of the click commands, since the private key is not optional.
The option is added by this function [which makes sets the argument as required](https://github.com/raiden-network/raiden-contracts/blob/e782e59df01f67e2caa8c412885922819da02576/raiden_contracts/deploy/__main__.py#L63)

private_key is not an optinal argument

---

raiden_contracts/deploy/__main__.py

This allows one to use a path with `~` in it. Which can be important for
scripts that use double quotes to escape variables with space in it,
e.g.:
python -m raiden_contracts.deploy raiden --private-key "$PRIVATE_KEY"

Added expanduser to the private key file

---

raiden_contracts/tests/fixtures/channel.py
requirements.txt

AFAICS it does not serve any purpose and it's slow.
Removes one call to `mine` after creating a channel.
To simplify and speed up tests.
Why has it been added it the first place?
----
* Bookkeep

Remove unnecessary `mine` in `create_channel`

---

Makefile
setup.py

Fix CompileContracts command and enable all linters for `setup.py` as well.
This appeared in multiple PRs already.
----
* Bookkeep

Fix CompileContracts command

---

raiden_contracts/deploy/__main__.py
raiden_contracts/tests/test_deploy_script.py

Fixes https://github.com/raiden-network/raiden-contracts/issues/1295
----
* Bookkeep

Require `--service-registry-controller` in deployer

---

CHANGELOG.md
raiden_contracts/constants.py
raiden_contracts/contract_manager.py
raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/deploy/etherscan_verify.py
raiden_contracts/tests/deprecation_switch_testnet.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/tests/test_etherscan_verify.py

Add support for verifying TokenNetworks registered via the TokenNetworkRegistry. This is a bit more involved since the TokenNetworks are not deployed by the python code, but by the TokenNetworkRegistry. So we have to reconstruct the argument list.
TODOs left for the next PR:

Verify token networks

---

.bumpversion.cfg
setup.py

Bump the PyPi version of `raiden-contracts` to `0.37.0b2`.
This will allow us to upload a new beta release to PyPi
I used `bump2version --config-file .bumpversion.cfg --new-version '0.37.0-beta2' 0.37.0-beta2`, but still had to
manually adjust the `VERSION` constant in `setup.py`. Maybe there are other places, that I missed?
----
* Bookkeep

Bump version: 0.37.0-beta → 0.37.0b2

---

requirements-dev.txt
requirements.txt

This could be avoided by importing it in an `if TYPING` block, but I'm
afraid people would forget and break the package. Therefore, I am more
comfortable with putting it into the normal requirements, although it is
not strictly necessary.

Move mypy-extensions into requirements.txt

---

Makefile
raiden_contracts/constants.py
raiden_contracts/tests/fixtures/channel.py
raiden_contracts/tests/test_etherscan_verify.py
raiden_contracts/tests/test_monitoring_service.py
raiden_contracts/tests/test_one_to_n.py
raiden_contracts/tests/test_print_gas.py
raiden_contracts/tests/unit/test_recover_from_signature.py
raiden_contracts/tests/utils/constants.py
raiden_contracts/utils/proofs.py
raiden_contracts/utils/signature.py
raiden_contracts/utils/type_aliases.py

These can be imported from Raiden, so that both packages share the same
types for basic Raiden objects.

Move basic Raiden types and start using them

---

raiden_contracts/tests/fixtures/base/utils.py
raiden_contracts/tests/test_deploy_script.py
raiden_contracts/utils/signature.py

The types are declared as bytes, so the actual runtime code should use bytes, too!
Followup of the type cleanup in https://github.com/raiden-network/raiden-contracts/pull/1394.

Use byte PrivateKey instead of hex encoded strs

---

raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/tests/test_deprecation_switch.py

Remove the last usage of the `deploy_contract` fixture and remove it.
Preparation for https://github.com/raiden-network/raiden-contracts/issues/401
----
* Bookkeep

Remove last usage of `deploy_contract` and remove it

---

raiden_contracts/constants.py
raiden_contracts/contract_manager.py
raiden_contracts/data/deployment_goerli_unstable.json
raiden_contracts/data/deployment_services_goerli_unstable.json

This allows us to run a second set of services without sharing the same
service registry.
Closes https://github.com/raiden-network/raiden-contracts/issues/1438

Add unstable deployment on goerli

---

.bumpversion.cfg
CHANGELOG.md
setup.py

This makes the new goerli deployment available for use in https://github.com/raiden-network/raiden/issues/6862.

Release 0.37.2

---

Makefile
RELEASE.rst
requirements-dev.txt

This will build and upload the PyPI package. In the past, this was done
by travis. If we want to automate this again, this make target can be
used.

Add `make upload-pypi` command

---

raiden_contracts/deploy/contract_deployer.py
raiden_contracts/tests/fixtures/contracts.py
raiden_contracts/utils/linking.py

Packages that use raiden-contracts' fixtures don't need a solc
installation, anymore. This is achieved by doing the linking step in
pure python.

Remove the need for local solc install for users

---

setup.py

This PR will fix the `setup.py` installation method by providing the necessary dependencies for the verify_contracts command that is employed during setup.
(see https://github.com/raiden-network/raiden-services/pull/951#issuecomment-814959179)

Fix setuptools setup_requires

---

README.rst
raiden_contracts/contract_source_manager.py

Developers won't have to manually install solc, anymore.
Replaces #1452.

Automatically install solc via solcx

---

raiden_contracts/deploy/contract_verifier.py
raiden_contracts/tests/test_deploy_script.py

Fix deployment check for old deployments
I ran into this while working on https://github.com/raiden-network/light-client/issues/2699
----
* Bookkeep

Fix deployment check for old deployments

---

.github/workflows/python-package.yml
CHANGELOG.md
README.rst
setup.py

Signal support for Python 3.9
----
* Bookkeep

Add support for python 3.9

---

raiden_contracts/deploy/__main__.py

We promised to use RDN during the token sale. We can't prevent anyone
from deploying the contracts with a different token selected, but we can
at least choose RDN as default.
Closes https://github.com/raiden-network/raiden-contracts/issues/1463.

Use RDN as default token for service payments

---

Makefile

Seems like the problems are fixed and we can use the new reolver now
----
* Bookkeep

chore: Use new pip resolver

---

raiden_contracts/utils/transaction.py

Otherwise we could wait additional 5s upon getting transaction receipt.
----
* Bookkeep

utils: only wait if we didn't find the transaction

---

raiden_contracts/contract_source_manager.py

This seems to be fixed in `py-solc-x`.
Remove the hack to remove the AST from the contract data.
Fix a small TODO in the code.
----
* Bookkeep

Remove hack to remove ast from contract data

---

raiden_contracts/utils/join_contracts.py

Before only the first prama was handled, and all later ones omitted.

Handle multiple pragmas in `ContractJoiner`

---

raiden_contracts/constants.py

Change the CONTRACTS_VERSION to 0.38.0.
So that raiden uses the latest released contract code.
:warning: This PR should not be merged until we are reasonably sure that the newer contracts will not break tests in the `raiden` repository.

raiden_contracts: change CONTRACTS_VERSION to 0.38.0

---

.bumpversion.cfg
CHANGELOG.md
requirements.txt
setup.py

While working on the raiden-service-bundle I ran into this>:
```
synapse_1            |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
synapse_1            |   File "/synapse-venv/lib/python3.9/site-packages/raiden_synapse_modules/presence_router/pfs.py", line 21, in <module>
synapse_1            |     from raiden_contracts.contract_manager import get_contracts_deployment_info
synapse_1            |   File "/synapse-venv/lib/python3.9/site-packages/raiden_contracts/contract_manager.py", line 11, in <module>
synapse_1            |     from mypy_extensions import TypedDict
synapse_1            | ModuleNotFoundError: No module named 'mypy_extensions'
````

Add missing `mypy_extensions`  requirement

---

.bumpversion.cfg
CHANGELOG.md
setup.py

https://github.com/raiden-network/raiden-services/pull/1131 is blocked by these deps, so lets create a new release.

chore: Prepare 0.40.2

---

raiden_contracts/constants.py
raiden_contracts/data/deployment_rinkeby-arbitrum.json
raiden_contracts/data/deployment_services_rinkeby-arbitrum.json
raiden_contracts/deploy/__main__.py
raiden_contracts/deploy/contract_deployer.py
raiden_contracts/deploy/contract_verifier.py
raiden_contracts/tests/test_deploy_script.py

Superseeds #1542 (due to the massive changes recently a rebase was not possible)
This includes the fixed for the deployment tools to work with Arbitrum chains with a special handling for gas.

Deployment on Rinkeby Arbitrum

---

README.rst
raiden_contracts/deploy/contract_deployer.py

Closes #1608 
First of all, it is not necessary to programmatically set a fixed gas price value when detecting an Arbitrum network. The gas price gets already set by a commandline parameter and does not need any further doing. The default 5 Gwei
are enough for the current prices (test network). Else the user can/must set the value higher.
As the deployment tools are meant to run by hand and usually a developer of the team, it is not necessary to add any special gas price strategies as we do for the Raiden services. But to support the correct/better usage, the deployment documentation got extended for Arbitrum.

improve gas handling for Arbitrum based networks

---

raiden_contracts/deploy/etherscan_verify.py

Add API endpoint to verify Arbitrum One deployment.
I used it already and it works in practice. You can check the latest Arbitrum One contract addresses in `data/` on Arbiscan.

add API endpoint to verify Arbitrum One deployment
