.travis.yml, contracts/TokenNetwork.sol
fixes https://github.com/raiden-network/raiden-contracts/issues/7
Initial gas cost:
```
TokenNetwork.openChannel 110848
TokenNetwork.setDeposit 68243
TokenNetwork.closeChannel 106743
TokenNetwork.updateTransfer 67055
TokenNetwork.settleChannel 63017
```
Gas cost after fix:
```
TokenNetwork.openChannel 109253
TokenNetwork.setDeposit 67872
TokenNetwork.closeChannel 106133
TokenNetwork.updateTransfer 66588
TokenNetwork.settleChannel 62907
```
=> Compute mapping pointer once

.gitignore, raiden_contracts/contract_manager.py, raiden_contracts/tests/test_contract_manager.py
Some small style and annotation fixes for the contract manager.
- Update and add some type annotations
- Remove a comparison with `is True`
- Add some test cases for non-existant events and contracts
=> Update type annotations

raiden_contracts/contracts/TokenNetwork.sol, raiden_contracts/contracts/TokenNetworksRegistry.sol, raiden_contracts/contracts/lib/ECVerify.sol, raiden_contracts/contracts/test/CustomToken.sol, raiden_contracts/contracts/test/HumanStandardToken.sol, raiden_contracts/contracts/test/SignatureVerifyTest.sol, raiden_contracts/contracts/test/StandardToken.sol, raiden_contracts/contracts/test/UnlockTest.sol
fixes https://github.com/raiden-network/raiden-contracts/issues/43
=> Adopt recommended ending parenthesis code style

raiden_contracts/contracts/TokenNetwork.sol, raiden_contracts/tests/test_channel_settle.py
fixes https://github.com/raiden-network/raiden-contracts/issues/54
=> Fix settling when no balance proof was provided by non closing party

requirements.txt
- temporary fix until we make 3.0.0 work
=> Freeze solc to 2.1.0

raiden_contracts/contracts/MonitoringService.sol, raiden_contracts/contracts/RaidenServiceBundle.sol, raiden_contracts/tests/fixtures/__init__.py, raiden_contracts/tests/fixtures/monitoring_service.py, raiden_contracts/tests/fixtures/raiden_service_bundle.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/utils/config.py, raiden_contracts/utils/sign.py
Initial implementation of the Monitoring Service smart contracts in accordance to https://github.com/raiden-network/spec/issues/46.
Still WIP
=> [WIP] MS smart contract

raiden_contracts/contracts/EndpointRegistry.sol, raiden_contracts/tests/fixtures/endpoint_registry.py, raiden_contracts/utils/config.py, raiden_contracts/utils/events.py
fixes https://github.com/raiden-network/raiden-contracts/issues/82
=> Add EndpointRegistry contract

raiden_contracts/tests/test_channel_update_transfer.py
=> Adding test `updateNonClosingBalanceProof` with different `nonce`s 

raiden_contracts/tests/test_channel_close.py, raiden_contracts/tests/test_channel_unlock.py
=> Adding a unit test for channel-settlement and unlock cycles.

raiden_contracts/contracts/TokenNetwork.sol, raiden_contracts/tests/fixtures/channel.py, raiden_contracts/tests/test_channel_deposit.py, raiden_contracts/tests/test_channel_withdraw.py, raiden_contracts/tests/test_print_gas.py, raiden_contracts/utils/events.py
fixes https://github.com/raiden-network/spec/issues/80
=> Fix consistency for withdraw and deposit terms

.travis.yml, raiden_contracts/contract_manager.py, raiden_contracts/deploy/__main__.py, raiden_contracts/tests/fixtures/channel.py, raiden_contracts/tests/fixtures/token_network.py, raiden_contracts/tests/test_channel_close.py, raiden_contracts/tests/test_channel_cooperative_settle.py, raiden_contracts/tests/test_channel_deposit.py, raiden_contracts/tests/test_channel_open.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_unlock.py, raiden_contracts/tests/test_channel_update_transfer.py, raiden_contracts/tests/test_channel_withdraw.py, raiden_contracts/tests/test_endpointregistry.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/tests/test_print_gas.py, raiden_contracts/tests/test_recover_from_signature.py, raiden_contracts/tests/test_secret_registry.py, raiden_contracts/tests/test_token.py, raiden_contracts/tests/test_token_network.py, raiden_contracts/tests/test_token_network_registry.py, raiden_contracts/tests/utils.py, requirements.txt
=> Update deprecated web3 APIs

raiden_contracts/contracts/TokenNetworkRegistry.sol, raiden_contracts/deploy/__main__.py, raiden_contracts/tests/fixtures/contracts.py, raiden_contracts/tests/fixtures/token_network_registry.py, raiden_contracts/utils/config.py
=> Rename TokenNetworksRegistry to TokenNetworkRegistry

raiden_contracts/contract_manager.py
- added `get_contract()` method
~~- renamed `TokenNetworks` to `TokenNetwork`~~
=> Channel manager can return both abi+compiled

raiden_contracts/contracts/SecretRegistry.sol, raiden_contracts/tests/test_secret_registry.py, raiden_contracts/utils/events.py
=> Include secret in SecretRevealed event

raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol
Needed for #129, subtask of  #92.
=> Adding wrapper functions for all internals in TokenNetwork.

raiden_contracts/cm_test/test_contract_manager.py, raiden_contracts/contract_manager.py, raiden_contracts/deploy/__main__.py, raiden_contracts/tests/fixtures/channel_test_values.py, raiden_contracts/tests/fixtures/contracts.py, raiden_contracts/tests/fixtures/monitoring_service.py, raiden_contracts/tests/fixtures/raiden_service_bundle.py, raiden_contracts/tests/fixtures/test_contracts.py, raiden_contracts/tests/fixtures/token_network.py, raiden_contracts/tests/fixtures/token_network_registry.py, raiden_contracts/tests/fixtures/utils.py, raiden_contracts/tests/test_channel_close.py, raiden_contracts/tests/test_channel_cooperative_settle.py, raiden_contracts/tests/test_channel_deposit.py, raiden_contracts/tests/test_channel_open.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_unlock.py, raiden_contracts/tests/test_channel_update_transfer.py, raiden_contracts/tests/test_channel_withdraw.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/tests/test_print_gas.py, raiden_contracts/tests/test_recover_from_signature.py, raiden_contracts/tests/test_secret_registry.py, raiden_contracts/tests/test_token_network.py, raiden_contracts/tests/test_token_network_registry.py, raiden_contracts/tests/utils.py, raiden_contracts/utils/logs.py, raiden_contracts/utils/sign.py, requirements-dev.txt
Add flake8 plugins as in raiden, raiden-libs.
Needs to be merged after raiden-network/raiden-libs#92 since it depends on fixtures expecting `None` values now.
=> More flake8 plugins

raiden_contracts/tests/test_channel_close.py
Adds:
- test_close_first_participant_can_close
- test_close_second_participant_can_close
- test_close_first_argument_is_for_partner_transfer
Resolves #145 .
=> Migrates raiden/[...]/test_close.py.

.bumpversion.cfg, .bumpversion_contracts.cfg, raiden_contracts/contracts/MonitoringService.sol, raiden_contracts/contracts/RaidenServiceBundle.sol, requirements-dev.txt, setup.py
- add bumpversion config for contracts and `setup.py`
- bump eth-tester
=> Add bumpversion for contracts

raiden_contracts/tests/test_channel_open.py
=> Adds test_reopen_channel.

raiden_contracts/tests/test_token_network_registry.py
=> Adds test_create_erc20_token_network_twice_fails.

raiden_contracts/contracts/test/HumanStandardToken.sol, raiden_contracts/tests/fixtures/token.py, raiden_contracts/tests/test_token.py
Fixes the HumanStandardToken that was broken from my last PR
=> Fix HumanStandardToken

raiden_contracts/tests/test_channel_update_transfer.py
fixes https://github.com/raiden-network/raiden-contracts/issues/148
=> Resolve channel update transfer

raiden_contracts/tests/test_token.py
=> Adds token approve and allowance checks.

raiden_contracts/deploy/__main__.py
Very simple changes. POA added, deploys endpoint, registry, secret registry contracts.
=> POA added, deploys endpoint, registry, secret registry contracts.

raiden_contracts/contracts/lib/ECVerify.sol, raiden_contracts/deploy/__main__.py
Some fixes / updates discovered / used while deploying the contracts
=> Deploy fixes / updates

setup.py
=> Skip contract compilation if solc is unavailable

.bumpversion.cfg, setup.py
=> Bump version: 0.0.1 → 0.1.0

raiden_contracts/contracts/EndpointRegistry.sol, raiden_contracts/contracts/SecretRegistry.sol, raiden_contracts/contracts/TokenNetwork.sol, raiden_contracts/contracts/TokenNetworkRegistry.sol, raiden_contracts/contracts/Utils.sol
- SecretRegistry
- Utils
- TokenNetworkRegistry
- TokenNetwork
=> Fix natspec comments for core smart contracts

raiden_contracts/contracts/TokenNetwork.sol
Reorder functions for better readability, after the Solidity docs guidelines:
https://solidity.readthedocs.io/en/v0.4.24/style-guide.html#order-of-functions
- constructor
- fallback function (if exists)
- external
- public
- internal
- private
We still have some methods that are `external` and have not been moved to the top. Such as:
- state changing: `setTotalWithdraw` , `updateNonClosingBalanceProof`
- getters: `getChannelInfo`, `getChannelParticipantInfo`
I wouldn't move the channel-related state changing functions to the top because we actually have not discussed the visibility modifiers on the channel functions + the functions are ordered by channel state logic, which makes more sense to me.
Open to ideas about the getters. I chose to have them after all the `public` & `external` …
=> Reorder functions after Solidity docs guidelines

raiden_contracts/contracts/EndpointRegistry.sol, raiden_contracts/contracts/SecretRegistry.sol, raiden_contracts/contracts/TokenNetwork.sol, raiden_contracts/contracts/TokenNetworkRegistry.sol, raiden_contracts/contracts/Utils.sol
This is completely cosmetic and can be discarded, I only opened it to see if we want to have the limit, and if yes just merge this PR.
=> Compact comments to 80 chars

raiden_contracts/deploy/__main__.py
The deploy tool used to use the global CONTRACT_MANAGER which uses a precompiled archive if it's available.
This changes things to always use the current source when deploying.
=> Always deploy from source

raiden_contracts/contracts/TokenNetwork.sol
Doesn't need to be merged in master right now, as this changes the contracts code without any real benefits.
It can be delayed for after the internal audit.
=> Remove redundant variable

raiden_contracts/contracts/TokenNetwork.sol
Merging can be delayed for after next week.
=> Restrict getMaxPossibleReceivableAmount to pure

raiden_contracts/contracts/SecretRegistry.sol, raiden_contracts/contracts/TokenNetwork.sol
In the same line of thought as https://github.com/raiden-network/raiden-contracts/pull/234
=> Explicit casting bytes32(0x0)

raiden_contracts/contract_manager.py, raiden_contracts/tests/fixtures/contract_manager.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_unlock.py, raiden_contracts/tests/test_print_gas.py, raiden_contracts/tests/utils/contracts.py, raiden_contracts/tests/utils/utils.py, raiden_contracts/utils/utils.py
Fix a circular import and move a function that we now use in the main repo too out of the tests folder.
=> Follow up to raiden pr #1990

raiden_contracts/contracts/TokenNetwork.sol
fixes https://github.com/raiden-network/raiden-contracts/issues/243
=> Use assert in openChannel for checking channel data existence

raiden_contracts/contracts/TokenNetwork.sol
To be merged later if accepted.
=> setTotalWithdraw - use assert for deposit overflow

raiden_contracts/contracts/TokenNetwork.sol
The settlement algorithm was very hard to follow. I added detailed explanations.
Also related to https://github.com/raiden-network/spec/issues/110
=> Improve TokenNetwork settlement algorithm comments

raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_token_network.py, raiden_contracts/tests/test_token_network_registry.py
- more checks
- moved 1 test from `test_channel_settle` to `test_token_network`
=> Add more checks for contract variables

README.rst
Part of https://github.com/raiden-network/raiden-contracts/issues/62
Update Readme info on:
- installation
- usage
- compilation
- testing
=> Update Readme with usage & development info

raiden_contracts/constants.py
Fix https://github.com/raiden-network/raiden-contracts/issues/299
=> Move deployed addressed and network configs from client to constants

README.rst, raiden_contracts/deploy/__main__.py
Part of https://github.com/raiden-network/raiden-contracts/issues/62
- use precompiled contract data in deployment script
- verify that the precompiled data matches the contracts source code
- update deployment info in Readme
=> Readme deployment fix

README.rst
Part of https://github.com/raiden-network/raiden-contracts/issues/62
=> Add Readme disclaimer

raiden_contracts/contract_manager.py
As suggested in https://github.com/raiden-network/raiden-contracts/pull/295#discussion_r222720607
=> Remove redundant iterable->list conversion

.travis.yml
fixes https://github.com/raiden-network/raiden-contracts/issues/326
=> Update solc 0.4.23 -> 0.4.25 for travis tests

MANIFEST.in, Makefile
Fix manifest file after adding deployment info & multiple compiled data versions
=> Fix manifest file after adding deployment info & multiple compiled ver.

.bumpversion.cfg, setup.py
Changes: 
- https://github.com/raiden-network/raiden-contracts/pull/348 - Add required gas for creating a TokenNetwork in constants
- https://github.com/raiden-network/raiden-contracts/pull/345 - Etherscan verification script
=> Bump version: 0.7.0 → 0.8.0

README.rst, RELEASE.rst
The first draft is taken from https://github.com/raiden-network/raiden-contracts/issues/355#issuecomment-445464788.
=> Add a draft of a release process document

RELEASE.rst
fixes https://github.com/raiden-network/raiden-contracts/issues/371
=> Update release process documentation

raiden_contracts/tests/test_token_network.py
=> Add comments on the tests about TokenNetwork

raiden_contracts/tests/test_token.py
=> Add comments to test_token.py

raiden_contracts/tests/deprecation_switch_testnet.py, raiden_contracts/tests/test_channel_open.py, raiden_contracts/tests/test_channel_settle_unlock_state.py, raiden_contracts/tests/test_contracts_compilation.py, raiden_contracts/tests/test_deploy_script.py
I think after this PR I can call #387 done. I didn't document the tests that are not executed now.
=> Document the remaining tests

raiden_contracts/deploy/__main__.py
See
* https://github.com/raiden-network/raiden-contracts/pull/396#discussion_r245663360
=> Better name and position of mypy auxiliary classes

raiden_contracts/deploy/__main__.py, raiden_contracts/utils/private_key.py
=> Remove a raiden-libs dependency: get_private_key

README.rst
fixes https://github.com/raiden-network/raiden-contracts/issues/398
=> Add note about deploying on a private chain in README

raiden_contracts/contract_manager.py
fixes https://github.com/raiden-network/raiden-contracts/issues/412
- raise an error if the version was downgraded
- allow for a rewrite of the precompiled data if the previous file is removed
=> Compare solc version used for compiling with the precompiled version

RELEASE.rst
This PR adds a paragraph in `RELEASE.rst` about finding the last release.
=> Add a paragraph about finding the last release

CONTRIBUTING.md
Part of https://github.com/raiden-network/raiden-contracts/issues/453
This PR only adds some code style references.
=> Started contribution guide, added code style references

RELEASE.rst
When I tried the release procedure #446 , I forgot to take this step.
=> git add deployment data before bumping package ver

README.rst
fixes https://github.com/raiden-network/raiden-contracts/issues/460
=> Update README with info about using the services contracts API

CONTRIBUTING.md
fixes https://github.com/raiden-network/raiden-contracts/issues/471
Info about what needs to be changed/updated when a new smart contract is added.
I hope I covered everything, but this can be tested and improved when adding the UDC contract.
=> Add info about adding a new contract to CONTRIBUTING.md

MANIFEST.in
This is a part of https://github.com/raiden-network/raiden-contracts/issues/470
=> Include Changelog.md in MANIFEST.in

CHANGELOG.md, CONTRIBUTING.md, RELEASE.rst
Also trying to remember to care about CHANGELOG.md while reviewing PRs
and making releases.
=> Mending Changelog

raiden_contracts/deploy/__main__.py
After this PR, `python -m raiden_contracts.deploy services` deploys a `UserDeposit` contract.
Fixes #499.
=> Deploy UDC during service deploy

raiden_contracts/deploy/__main__.py
This closes https://github.com/raiden-network/raiden-contracts/issues/501.
=> Factor out a function to read receipts

raiden_contracts/deploy/__main__.py
This is a part of #482 .  I tried the script with Kovan.
=> Call UserDeposit.init() during the service contract deployment

CONTRIBUTING.md
Echoing @karlb 's [comment](https://github.com/raiden-network/raiden-contracts/pull/512#discussion_r253828354).
[skip ci]
=> Mention type annotations in the pull-request guide

README.rst
[no ci]
This closes https://github.com/raiden-network/raiden-contracts/issues/490
=> Note Byzantium version is necessary

raiden_contracts/deploy/__main__.py
This PR is a further refactoring on the deployment script.
This gets us closer to calling https://github.com/raiden-network/raiden-contracts/issues/501 done.
I tested deployment+etherscan verification on this PR.
=> Refactor similar lines deploying contracts

RELEASE.rst
with the learning gained during 0.10.0 release process.
[skip ci]
=> Update the release process document

raiden_contracts/deploy/__main__.py
This follows an idea from
https://github.com/raiden-network/raiden-contracts/issues/501
=> Further simplify the deploy script

raiden_contracts/tests/test_channel_close.py, raiden_contracts/tests/test_channel_open.py, raiden_contracts/tests/utils/channel.py
Each commit adds one more check in the CI tests.  Making sure an event is fired, or checking the post-state and so on.
=> More checks in CI tests

raiden_contracts/contracts/test/MonitoringServiceInternalsTest.sol, raiden_contracts/data/contracts.json, raiden_contracts/tests/fixtures/monitoring_service.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/utils/events.py
* Extract basic setup into fixture
* Split single test into multiple tests
* Provide test contract to access private function
* Include checks for error cases in tests
Closes #56
=> Improve MSC tests

.gitignore, .travis.yml, Makefile, raiden_contracts/contract_manager.py, raiden_contracts/contracts/lib/ECVerify.sol, raiden_contracts/contracts/raiden/EndpointRegistry.sol, raiden_contracts/contracts/raiden/SecretRegistry.sol, raiden_contracts/contracts/raiden/Token.sol, raiden_contracts/contracts/raiden/TokenNetwork.sol, raiden_contracts/contracts/raiden/TokenNetworkRegistry.sol, raiden_contracts/contracts/raiden/Utils.sol, raiden_contracts/contracts/services/MonitoringService.sol, raiden_contracts/contracts/services/OneToN.sol, raiden_contracts/contracts/services/ServiceRegistry.sol, raiden_contracts/contracts/services/UserDeposit.sol, raiden_contracts/contracts/test/CustomToken.sol, raiden_contracts/contracts/test/HumanStandardToken.sol, raiden_contracts/contracts/test/MonitoringServiceInternalsTest.sol, raiden_contracts/contracts/test/SignatureVerifyTest.sol, raiden_contracts/contracts/test/StandardToken.sol, raiden_contracts/contracts/test/TokenNetworkInternalsTest.sol, raiden_contracts/contracts/test/UDCTransfer.sol, raiden_contracts/tests/test_deploy_script.py, requirements-dev.txt, setup.py
This PR removes
* the unlimited flavor, and
* the mustache template mechanism.
=> Remove flavors Part 1

CONTRIBUTING.md
As suggested in #453, this issue adds more Solidity related information in the contribution guide.
[skip ci]
=> Add more Solidity info in the contribution guide

.gitignore, .travis.yml, requirements-dev.txt
=> Adding coverage measurements

raiden_contracts/contract_manager.py, raiden_contracts/deploy/__main__.py, raiden_contracts/deploy/etherscan_verify.py, raiden_contracts/tests/test_channel_close.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_withdraw.py, raiden_contracts/tests/test_token.py, raiden_contracts/utils/proofs.py
This is a part of
https://github.com/raiden-network/raiden-contracts/issues/643
=> Use more keyword arguments

raiden_contracts/tests/test_contracts_compilation.py
This might make Codecov happy in #669 .
=> Test ContractManager more

raiden_contracts/tests/test_contracts_compilation.py
This PR proposes a simpler way to mutate a string.
=> An easier way to modify a string

raiden_contracts/tests/test_deploy_data.py
My `pylint` suddenly started detecting more double quotes.
=> More single quotes

README.rst
I'm trying to make it easier to figure out the addresses of the deployed contracts.
=> How to find addresses of deployed contracts

CONTRIBUTING.md, RELEASE.rst
This fixes https://github.com/raiden-network/raiden-contracts/issues/745.
=> Fix contribution guide about which file to edit

README.rst
This PR adds an FAQ entry: how to mint test tokens.
[skip ci]
=> Explain how to mint test tokens

CHANGELOG.md, README.rst, raiden_contracts/deploy/__main__.py, raiden_contracts/tests/test_contracts_compilation.py, raiden_contracts/tests/test_deploy_script.py
This closes https://github.com/raiden-network/raiden-contracts/issues/621 .
=> Rename --registry into --token-network-registry

raiden_contracts/deploy/__main__.py, raiden_contracts/deploy/contract_deployer.py
I am trying to mitigate #714 now.
=> Split ContractDeployer to its own file

raiden_contracts/utils/logs.py
This is a response to CodeClimate's warning https://github.com/raiden-network/raiden-contracts/issues/715 .
The diff looks rather horrible for what it is.  I moved some lines from `handle_log()` into a new function `_handle_waited_log()`.
=> Split a too deeply indented funciton handle_log

.bumpversion.cfg, CHANGELOG.md, setup.py
I'm cutting a release now to push https://github.com/raiden-network/raiden-contracts/issues/778 forward.
=> 0.16.0 Release

raiden_contracts/deploy/__main__.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/tests/deprecation_switch_testnet.py, raiden_contracts/tests/test_deploy_script.py
This is for calming down CodeClimate
https://github.com/raiden-network/raiden-contracts/issues/714
=> Move deploy_token_contract into ContractDeployer

raiden_contracts/contract_manager.py
This PR introduces more `DeployedContracts` type annotations.
Somehow https://github.com/raiden-network/raiden-contracts/pull/798 woke up `mypy` and it started complaining about this.
=> Type-annotate get_contracts_deployment_info()

raiden_contracts/deploy/__main__.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/tests/deprecation_switch_testnet.py, raiden_contracts/tests/test_deploy_script.py
from __main__.py.
This is a part of https://github.com/raiden-network/raiden-contracts/issues/714
=> Move deploy_ functions into ContractDeployer

raiden_contracts/deploy/etherscan_verify.py, raiden_contracts/tests/test_etherscan_verify.py
There was a while loop in the body of an if statement, and
probably this increased the code complexity.
This commit pulls the while loop out of the if statement.
Probably this makes CodeClimate happier.
=> Pull out a while loop in an if-statement

raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_verifyer.py, raiden_contracts/tests/test_token.py, raiden_contracts/utils/__init__.py, raiden_contracts/utils/bytecode.py
=> Move runtime_code() function into ContractManager

raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/deploy/contract_verifyer.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_deploy_script.py, raiden_contracts/tests/unit/test_files.py
=> Replace some asserts with if-statements

raiden_contracts/deploy/etherscan_verify.py
This fixes https://github.com/raiden-network/raiden-contracts/issues/687
=> Add all contracts in help message of etherscan_verify

raiden_contracts/tests/unit/test_web3_interaction.py
=> Test to see call_and_transact() mines a block

raiden_contracts/deploy/__main__.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_data.py
=> Fix English verifyer-->verifier

raiden_contracts/deploy/__main__.py, raiden_contracts/tests/test_deploy_script.py
with an explicit exception raising.
I made changes in `deploy/__main__.py` and tried to satisfy Codecov.  As a side-effect the code coverage increased by 2%.
=> Replace asserts that might fail

raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_deploy_script.py
with if statements.
This is a part of https://github.com/raiden-network/raiden-contracts/issues/847.
I'm expecting a Codecov failure, and I'll add tests.
=> Replace asserts in _verify_deployed_contract()

CONTRIBUTING.md
the contribution guide.
this closes #887.
=> Explain Solidity assert() and require() in

raiden_contracts/utils/mint_tokens.py
Just a small utility to mint tokens please review it.
=> Utility for minting tokens from CustomToken Contracts

raiden_contracts/contract_manager.py, raiden_contracts/tests/test_contracts_compilation.py
=> Nicer error message for missing contracts

.travis.yml, raiden_contracts/utils/mint_tokens.py
Somehow `black --check` failed on `master`. This PR fixes it.
=> Fix black --check

raiden_contracts/contract_source_manager.py, raiden_contracts/tests/test_contracts_compilation.py, raiden_contracts/tests/test_deploy_data.py
I expect CodeCov to complain.  After that, I'll add a test to cover the additional case.
=> Remove an assertion that might fail

raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_transaction.py, raiden_contracts/tests/unit/test_unit_internals.py, raiden_contracts/tests/unit/test_web3_interaction.py, raiden_contracts/utils/events.py, raiden_contracts/utils/logs.py, raiden_contracts/utils/merkle.py, raiden_contracts/utils/proofs.py, raiden_contracts/utils/signature.py, raiden_contracts/utils/transaction.py
=> Add a lot of type annotations

raiden_contracts/tests/test_deploy_script.py
contracts_version.
This is a part of https://github.com/raiden-network/raiden-contracts/issues/770
=> Add a test to call the deploy script with 0.4.0

raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/tests/fixtures/contracts.py, raiden_contracts/tests/test_contracts_compilation.py, raiden_contracts/tests/test_etherscan_verify.py, raiden_contracts/tests/test_transaction.py, raiden_contracts/utils/events.py, raiden_contracts/utils/proofs.py
=> Add more type annotations

raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_deploy_script.py
verify_service_contracts_deployment_data()
I'm first expecting a CodeCov failure.
=> Replace asserts with if statements in verify_service_contracts_deployment_data()

raiden_contracts/tests/fixtures/base/contract_manager.py, raiden_contracts/tests/test_deploy_data.py
=> Prevent tests from writing to contracts.json

Makefile
during make lint runs
The change is a copy of https://github.com/raiden-network/raiden/pull/4075/files
This closes #977.
=> Make black more informative

raiden_contracts/tests/test_deploy_script.py
=> Add a test that touches deploy verify command

raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/tests/fixtures/monitoring_service.py, raiden_contracts/tests/fixtures/user_deposit.py, raiden_contracts/tests/test_contract_limits.py, raiden_contracts/tests/test_endpointregistry.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/tests/test_print_gas.py, raiden_contracts/tests/test_service_registry.py, raiden_contracts/tests/test_token.py, raiden_contracts/tests/test_user_deposit_contract.py, raiden_contracts/tests/unit/test_recover_from_signature.py, raiden_contracts/tests/unit/test_unit_internals.py
This PR adds type annotations to functions.  This is a part of #918.
=> Random type annotations

raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_deploy_script.py, raiden_contracts/tests/test_etherscan_verify.py, raiden_contracts/tests/unit/test_web3_interaction.py, raiden_contracts/tests/utils/constants.py, raiden_contracts/utils/__init__.py, raiden_contracts/utils/events.py, raiden_contracts/utils/logs.py, raiden_contracts/utils/proofs.py, raiden_contracts/utils/type_aliases.py
to match the names in the Raiden client codebase.
=> Rename Address into AddressHex

raiden_contracts/tests/test_deploy_script.py
=> Add a test that touches the deploy register script

raiden_contracts/deploy/__main__.py, raiden_contracts/tests/test_deploy_script.py
This is a part of https://github.com/raiden-network/raiden-contracts/issues/847
I expect CodeCov to complain.  Then I'll add a test that touches the new code path.
=> Turn a failable assert into an if statement

raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_script.py
Look one line above, and the assert obviously holds.
=> Remove a too obvious assert

raiden_contracts/utils/pending_transfers.py
=> Add types to fields of PendingTransfersTree

MANIFEST.in
Otherwise the new API gas_measurements() doesn't work.
This fixes #1033.
=> Add gas.json in the packages

raiden_contracts/deploy/__main__.py, raiden_contracts/tests/deprecation_switch_testnet.py, raiden_contracts/tests/fixtures/base/address.py, raiden_contracts/tests/fixtures/base/web3_fixtures.py, raiden_contracts/tests/fixtures/channel.py, raiden_contracts/tests/fixtures/contracts.py, raiden_contracts/tests/fixtures/monitoring_service.py, raiden_contracts/tests/fixtures/token_network_fixtures.py, raiden_contracts/tests/fixtures/token_network_registry.py, raiden_contracts/tests/test_channel_close.py, raiden_contracts/tests/test_channel_deposit.py, raiden_contracts/tests/test_channel_open.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_unlock.py, raiden_contracts/tests/test_channel_update_transfer.py, raiden_contracts/tests/test_channel_withdraw.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_deploy_script.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/tests/test_one_to_n.py, raiden_contracts/tests/test_print_gas.py, raiden_contracts/tests/unit/test_recover_from_signature.py, raiden_contracts/tests/unit/test_settle_timeout_invariant.py, raiden_contracts/tests/unit/test_unit_signatures.py
=> Add type annotations

raiden_contracts/contract_manager.py, raiden_contracts/tests/unit/test_merge_dict.py
I'm expecting a Codecov failure first.  Then I'll add a test to fix that.
=> An assert might fail, so replacing with if: raise

README.rst
=> Add an FAQ entry about block gas exceeded

README.rst, raiden_contracts/tests/README.md
of the topmost directory.
This closes #1001.
=> Move the directory structure to README

MANIFEST.in, raiden_contracts/CHANGELOG.md
so CHANGELOG.md will be included in the package.
Thsi is a part of #470.
=> Add a symlink to Changelog in the package

raiden_contracts/constants.py, raiden_contracts/deploy/etherscan_verify.py
=> Move CONTRACT_LIST to constants.py

pytest.ini
=> Register pytest mark slow

CHANGELOG.md, raiden_contracts/constants.py, raiden_contracts/contract_manager.py, raiden_contracts/deploy/contract_verifier.py, raiden_contracts/deploy/etherscan_verify.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_settle_unlock_state.py, raiden_contracts/tests/test_channel_unlock.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/utils/__init__.py, raiden_contracts/utils/type_aliases.py
=> Type-annotate `ChainID`

raiden_contracts/utils/logs.py
=> LogHandler uses click.echo instead of print()

raiden_contracts/utils/token_ops.py
…ng tokens on private or testnet environment
=> Commonly used token operations like minting, getting weth, transferring tokens

raiden_contracts/tests/fixtures/base/utils.py, raiden_contracts/tests/fixtures/channel.py, raiden_contracts/tests/test_channel_deposit.py, raiden_contracts/tests/test_channel_settle.py, raiden_contracts/tests/test_channel_settle_unlock_state.py, raiden_contracts/tests/test_channel_unlock.py, raiden_contracts/tests/test_deprecation_switch.py, raiden_contracts/tests/unit/test_merge_dict.py, raiden_contracts/tests/unit/test_recover_from_signature.py, raiden_contracts/utils/logs.py, raiden_contracts/utils/token_ops.py, setup.cfg
=> Type-annotate all functions

README.rst
=> Documenting minting and allied utilities

.bumpversion.cfg, CHANGELOG.md, setup.py
This contains more gas measurements on CustomToken functions.
=> Release 0.25.1

raiden_contracts/tests/test_channel_deposit.py
into more informative names.
This fixes #1074.
=> Rename A_deposit and deposit_A

raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_script.py
an if not ...: raise ...
I think CodeCov will complain.  Then I'll add the missing test.
=> Turn actual check from an assert into

raiden_contracts/contract_source_manager.py, raiden_contracts/tests/unit/test_unit_internals.py
=> Compilation fails on too big runtime code

raiden_contracts/tests/test_channel_deposit.py
Many tests in test_channel_deposit.py did not check the state
of TokenNetwork after calling setTotalDeposit().  This commit
adds those checks.  In the course a bug was also fixed.
This closes #1073.
=> Check storage after setTotalDeposit

.bumpversion.cfg, CHANGELOG.md, setup.py
This release just contains some package upgrades.  However, when you import this version, you might need to type-annotate more functions.
=> 0.29.1 release

CONTRIBUTING.md
=> Enrich PR checklist

CONTRIBUTING.md, raiden_contracts/tests/test_service_registry.py
as bump denominator.
This commit is a part of solving #581.
=> Add a test creating ServiceRegistry with zero

raiden_contracts/tests/test_service_registry.py
=> Test too big duration so overflow happens

raiden_contracts/tests/test_service_registry.py
I forgot to add comments on some new tests.  I add them here.
=> Comment new tests

raiden_contracts/tests/test_service_registry.py
Then the current price becomes the new min price.
=> Test setting the min price above the current price

CONTRIBUTING.md, pull_request_template.md
That contains a checklist that a reviewer is supposed to tick off.
This closes #1154.
=> Add a PR template

raiden_contracts/tests/fixtures/token.py
This closes #1206.  This contract will be useful for checking
one of the `require()` conditions in the constructor of TokenNetwork.
This PR adds a fixture that deploys a CustomToken contract with zero initial supply.
I want to write a test case that registers such a token to TokenNetworkRegistry https://github.com/raiden-network/raiden-contracts/issues/581.  I expect failure.
`custom_token_factory()` does not allow changing the initial supply.  So I could not use it.
----
* Bookkeep
=> Implement a test Token with zero supply

.bumpversion.cfg, CHANGELOG.md, setup.py
Bumps the version number to 0.33.1.
There was a missing line in `MANIFEST.in` (fixed in #1288).  So I'm making the release again.
Nothing. A very simple release PR.
----
=> Release 0.33.1

CONTRIBUTING.md
This closes #888.
Adds a sentence in the contribution guide.
By requested in #888.
Nothing.
----
=> One function one thing

raiden_contracts/deploy/contract_verifier.py, raiden_contracts/tests/test_deploy_data.py, raiden_contracts/tests/test_deploy_script.py, raiden_contracts/utils/versions.py
This closes #1274.
This PR adds a space between words.
I saw "verifiedand".
Nothing.
----
=> Add a space between words

README.rst, raiden_contracts/tests/test_monitoring_service.py
=> Add missing args in the docs for deployment of services contracts

.github/auto_assign.yml
This adds the configuration for the auto assign bot.
=> Added auto_assign

raiden_contracts/deploy/etherscan_verify.py
When using the default user agent, Etherscan blocks our requests. Using
a curl user agent avoids this.
Also print the response when it is not a valid JSON response for easier
debugging in such a case.
----
* Bookkeep
=> Avoid being blocked by cloudflare/etherscan

README.rst
Fix formatting in README
----
* Bookkeep
=> Fix formatting in readme

.github/auto_assign.yml
=> Update reviewers list

.bumpversion.cfg, CHANGELOG.md, setup.py
Release 0.36.1
----
* Bookkeep
=> Release 0.36.1

raiden_contracts/constants.py, raiden_contracts/contract_manager.py, raiden_contracts/tests/test_contracts_compilation.py
See https://github.com/raiden-network/raiden/issues/1515
----
* Bookkeep
=> Rename network to chain

.bumpversion.cfg, setup.py
=> Bump version: 0.36.1 → 0.36.2

.travis.yml, requirements-dev.txt
Show info about running tests in travis.
=> Run without `travis_wait`

raiden_contracts/data/deployment_mainnet.json, raiden_contracts/data/deployment_services_mainnet.json
Do not use these contracts except for Brainbot internal testing, the
deprecation switch will be triggered soon!
----
* Bookkeep
=> Prepare beta2 release [WIP]

raiden_contracts/deploy/__main__.py, raiden_contracts/tests/deprecation_switch_testnet.py
Without this, you will be prompted for the password.
Closes https://github.com/raiden-network/raiden-contracts/issues/1367
=> Deploy script now optionally takes `password-file`

raiden_contracts/constants.py
See https://github.com/raiden-network/raiden-services/issues/787
See https://github.com/raiden-network/raiden-contracts/blob/master/raiden_contracts/data_0.37.0/source/raiden/TokenNetwork.sol#L141
=> Add deprecation event to ChannelEvent

.bumpversion.cfg, setup.py
Creates a commit with the bumped version.
To make an RC of the Raiden package, the changes to the contracts repo are used by the Raiden repo.
Nada
----
* Bookkeep
=> Bump version: 0.37.0 → 0.37.1

raiden_contracts/deploy/contract_deployer.py, raiden_contracts/tests/fixtures/base/utils.py, raiden_contracts/tests/fixtures/base/web3_fixtures.py, raiden_contracts/tests/test_monitoring_service.py, raiden_contracts/tests/utils/address.py, raiden_contracts/tests/utils/constants.py, raiden_contracts/utils/mint_tokens.py, raiden_contracts/utils/private_key.py, raiden_contracts/utils/signature.py
As requested in https://github.com/raiden-network/raiden-services/pull/800.
=> Make get_random_privkey return a PrivateKey

raiden_contracts/deploy/etherscan_verify.py, raiden_contracts/tests/test_etherscan_verify.py, requirements-dev.txt
That call needs an api key too, now.
=> Pass etherscan api key to checkverifystatus

raiden_contracts/data/deployment_goerli.json, raiden_contracts/data/deployment_services_goerli.json
If we want to run it on the testnet, we need a deployment.
=> Deploy raiddit contracts to goerli

Makefile, raiden_contracts/tests/unit/test_recover_from_signature.py, raiden_contracts/tests/utils/contracts.py, raiden_contracts/utils/private_key.py, raiden_contracts/utils/signature.py, requirements-dev.txt
Fix some of the newly popped up mypy warnings. I don't know why they didn't pop up in the other PR, but here we go.
----
* Bookkeep
=> Mypy fixes

.github/workflows/python-package.yml
Increase parallelism in tests.
Reduce CI runtime from 12 to 8 minutes.
----
* Bookkeep
=> Run tests with 4 parallel processes

requirements.txt
Remove explicitly declared dependency, this gets pulled from web3.
Make deps cleaner.
----
* Bookkeep
=> Remove explicit py_ecc dependency

.github/workflows/python-package.yml
Install `ethlint`/`solium` in CI, so that it gets run during linting.
Make CI stricter.
----
* Bookkeep
=> Install ethlint/solium in CI

raiden_contracts/contract_source_manager.py, requirements-dev.txt, requirements.txt
Use `py-solc-x`	instead of unmaintained `py-solc`
Pulled out from https://github.com/raiden-network/raiden-contracts/pull/1428
Resolves https://github.com/raiden-network/raiden-contracts/issues/1427
----
* Bookkeep
=> Use `py-solc-x` instead of unmaintained `py-solc`

README.rst, raiden_contracts/contract_source_manager.py, raiden_contracts/deploy/__main__.py, raiden_contracts/deploy/contract_deployer.py, raiden_contracts/tests/test_deploy_script.py, requirements-dev.txt, requirements.txt
Fix https://github.com/raiden-network/raiden-contracts/issues/1182
Makes the reuse of the `ServiceRegistry` possible.
- Is there actually a point in re-suing the service registry, but deploying a new UDC?
----
* Bookkeep
=> Allow reuse service registry

.bumpversion.cfg, CHANGELOG.md, MANIFEST.in, setup.py
I didn't realize that the manifest was *that* selective.
=> Release 0.37.5

.github/workflows/python-package.yml
Increment the cache key in gh actions workflow.
Invalidate older CI caches.
=> Increment cache key version

.bumpversion.cfg, setup.py
=> Bump version: 0.37.5 → 0.37.6

requirements.txt
=> chore: remove unneccessary `mypy-extensions` dependency

Makefile, requirements-dev.txt
Overlaps with `black`, see also https://github.com/raiden-network/raiden/commit/47371dcac1913e250382306b312013856960922c
----
* Bookkeep
=> chore: Remove autopep8

raiden_contracts/data/deployment_mainnet.json, raiden_contracts/data/deployment_services_mainnet.json, raiden_contracts/data_0.40.0/deployment_mainnet.json, raiden_contracts/data_0.40.0/deployment_services_mainnet.json
Deploy more test contracts
----
* Bookkeep
=> Deploy more test contracts

.github/dependabot.yml
=> Add dependabot config for actions
